### ISSUE TITLE
interact issue with black.mpq

### ISSUE THREAD

**Issue by isfanom** [isid0re/SoloLeveling#10]
There r some problems with interacting NPC with using black mode(changed mpq or direct txt or both, u know. dont know how can i say) to reduce cpu resources.
In act1, killed andariel and tried to interact warriv but if it failed(high possibilities), there comes "couldn't access the level", and in the next room, character tries to use waypoint to get to act2. and it fails ofc.
U have any idea about this or should i not use the black mode? Also server is not good anyway to deal with interact. If it could't interact right in the first game there will be much more problems.

**Comment by isid0re** [comment]
I'm not very familiar with the black  modifications you are referencing. Based on what I understand from your explanation, it disabled the screen view to reduce CPU usage. 

If that is the case there exists a possibility that the way kolbot interacts using the click function wont work. Without actually testing, I cant say for sure. But if that is the case then a possible solution would be to use the  sendpacket option. 

Thanks for submitting this matter. I will investigate it further.

**Comment by isfanom** [comment]
I tested it more with normal mpq(not black) with lots of clients, interact problems occur at low probability also. IMHO, it will be good if there r some safe orders to access the next level like which if a character cant get to the next level through the waypoint, make it to interact with the NPC again.

**Comment by isid0re** [comment]
Thanks for investigating. I will implement the access check in the next commit

**Comment by isid0re** [comment]
The update has been submitted with portal and npc checks for interactions. Please update to the most recent version in the repository. Thanks.
