### ISSUE TITLE
I do not log in

### ISSUE THREAD

**Issue by ASSAMAN-PS** [isid0re/SoloLeveling#100]
Stuck at the login screen

**Comment by isid0re** [comment]
Are you using the repo pushed from 4 hours ago? If not please update and let me know if it continues to not log in.

**Comment by ASSAMAN-PS** [comment]
I don't log in after update

**Comment by isid0re** [comment]
Please describe in detail what is happening.
Are you using your personal account and password?
A randomly generated one?
Does it fail to login when it is to make the character?
Or is it failing to logon after a chicken or d2bs crash?

Please provide as much detail as possible so I can try and replicate your problem. 

Thank you.

**Comment by isid0re** [comment]
I just pushed an update to fix the login issues. please update your files and let me know if this continues. thanks.

**Comment by ircopdd** [comment]
> 我剛剛推送了一個更新來解決登錄問題。請更新您的文件，並讓我知道是否繼續。謝謝。

Commits on Feb 13, 2021  is work 

after Commits  can't sign in

**Comment by isid0re** [comment]
Thank you.

**Comment by isid0re** [comment]
Just pushed a tested and confirmed working entry script with users who also had login problems. Should be resolved now

**Comment by ircopdd** [comment]
> Just pushed a tested and confirmed working entry script with users who also had login problems. Should be resolved now

no work for me

use 193 commits  
all bot 

D2BS is not responding... starting profile
