### ISSUE TITLE
Can only run one sin bot?

### ISSUE THREAD

**Issue by ircopdd** [isid0re/SoloLeveling#105]
![2021-02-18_170057](https://user-images.githubusercontent.com/3633003/108332638-fcb6a600-720a-11eb-989f-afcc37769896.png)

SIN2 level 28 stop and auto exit game
![2021-02-18_124222](https://user-images.githubusercontent.com/3633003/108332769-25d73680-720b-11eb-9d5b-433df76c03d5.png)

![2021-02-18_124202](https://user-images.githubusercontent.com/3633003/108332914-4bfcd680-720b-11eb-9f9e-73e2eeeec578.png)

**Comment by isid0re** [comment]
Hmm thank you for posting this. There shouldn't be a limit on the number of bots. I will check a few things and see what can cause this.

**Comment by ircopdd** [comment]
193 commits
bot2 crash again
D2BS is not responding... starting profile
![2021-02-19_105132](https://user-images.githubusercontent.com/3633003/108450727-a1cf8e00-72a0-11eb-914b-28e8ad17bb22.png)

**Comment by isid0re** [comment]
Thank you I'm currently trying to recreate this error so I can fix it.

Does the sin2 crash at a specific location? Or time?

What is sin1 doing at the moment sin2 crashes? 

Thanks for your help.

**Comment by isid0re** [comment]
I just noticed your image is showing SCCL this reflects softcore classic ladder.  Assassin build is expansion only this will not work on classic. That should be why the bot is crashing. 

You will need the profile to be SCL-SIN for assassins

**Comment by ircopdd** [comment]
> Thank you I'm currently trying to recreate this error so I can fix it.
> 
> Does the sin2 crash at a specific location? Or time?
> 
> What is sin1 doing at the moment sin2 crashes?
> 
> Thanks for your help.

sin1 is work Perfect

sin2 "debugInfo":"{\"area\":\"Kurast Docktown\",\"currScript\":\"no entry\"}","setDifficulty":"Normal"}

sin2 start bot After crash

**Comment by ircopdd** [comment]
> I just noticed your image is showing SCCL this reflects softcore classic ladder. Assassin build is expansion only this will not work on classic. That should be why the bot is crashing.
> 
> You will need the profile to be SCL-SIN for assassins

no work

![2021-02-19_142315](https://user-images.githubusercontent.com/3633003/108466078-0a793380-72be-11eb-96dc-475fd076a78a.png)

**Comment by ircopdd** [comment]
i can join game now 

but auto exit game
https://youtu.be/XzuKfOahJAc

**Comment by isid0re** [comment]
Thanks for the video, it really helps to see what is going on. I had that happen before with the bot not getting access to act 5 cuz it glitched out. Please manually log into the game and confirm if diablo quest is completed. If so then talk with tirael and take the red portal to act 5. Then you can restart the bot and it should work. If it doesnt have access to diablo quest then somehow the same thing happened with mephisto and the red portal. I thought that I fixed the mephisto error has been previously. So please let me know if you needed to go thru the mephisto red portal or thru tiraels red portal. So I can update the scripts accordingly. 

Thanks.

**Comment by ircopdd** [comment]
> 感謝您的視頻，這確實有助於了解發生了什麼。我曾經在機器人無法訪問第5行為的情況下發生過這種情況，它突然出現了故障。請手動登錄遊戲並確認暗黑破壞神任務是否完成。如果是這樣，請與tirael交談，並使用紅色門戶進行操作5。然後您可以重新啟動bot，它應該可以工作了。如果它無法訪問暗黑破壞神任務，那麼墨菲斯托和紅色門戶網站又發生了同樣的事情。我以為我已經修復了mephisto錯誤。因此，請讓我知道您是否需要通過墨菲斯托紅色門戶或tiraels紅色門戶。因此，我可以相應地更新腳本。
> 
> 謝謝。
is tirael

![2021-02-19_151440](https://user-images.githubusercontent.com/3633003/108470894-980c5180-72c5-11eb-853b-30e7eb676e6d.png)
work now

15:15:17 (SCL-SIN6) D2BS is not responding... starting profile
15:15:29 (SCL-SIN6) D2BS is not responding... starting profile
15:15:40 (SCL-SIN6) D2BS is not responding... starting profile

but login need crash 3 times to enter the game

**Comment by isid0re** [comment]
Someone mentioned to me before that if the entry script is crashing try changing the entry to another entry script and once it enters the game. To turn if off and go back to the original script. You can try that and see if it clears your scripts crashing.

**Comment by ircopdd** [comment]
> Someone mentioned to me before that if the entry script is crashing try changing the entry to another entry script and once it enters the game. To turn if off and go back to the original script. You can try that and see if it clears your scripts crashing.

no work 

I can only wait crash 3 times to join game
