### ISSUE TITLE
"Status" Info on D2Bot (aka Kolbot)

### ISSUE THREAD

**Issue by CafeRacer400** [isid0re/SoloLeveling#11]
Please update the code that the current state of the char (area, lvl, gold,...) is shown up in the "Status" tab on D2Bot.
It seems stuck at "Make Game Delay (3s)".

**Comment by dakky221** [comment]
Add this to line 303 and 304 of D2BotLead.dbj

`					var diffName = ["N", "NM", "H"][me.diff];
					D2Bot.updateStatus("Working!" + timer(gameStart) + " | Lvl: " + me.charlvl + " | Gold: " + me.gold + " | (A" + me.act + ") " + Pather.getAreaName(me.area) + " | " + diffName + " | HP: " + me.hp + " | Ping: " + me.ping);`

Remove whatever you wish like HP.

**Comment by isid0re** [comment]
Dont forget to include both the Pather.js and Prototypes.js files into the entry script.
