### ISSUE TITLE
Followed instructions but bot never leaves town

### ISSUE THREAD

**Issue by molar131** [isid0re/SoloLeveling#113]
I followed every instruction i could find for this script, but he loads in and never leaves town. I have attached a screenshot of the bot's console messages from inside the game that gets created:

![kolbot](https://user-images.githubusercontent.com/79417847/108634712-dda55780-7448-11eb-8197-9c55ff846e11.PNG)

I pointed autobuild to the leveling profile, and fixed my battle config, but still never leaves town using the SoloLevelingEntry script. im new to this type of Bot, so im totally stumped

**Comment by theBGuy** [comment]
what do you mean? The way this is set up the only editing you should of had to do was add profile info in d2bot#

**Comment by molar131** [comment]
> what do you mean? The way this is set up the only editing you should of had to do was add profile info in d2bot#

So I extracted the profile as instructed into the correct folder, when i selected the profile D2BotSoloLevelingEntry.dbj, it entered the game and said, bad attack config.  i went into the folder for kolbot and it created a profile named class.charactername

so i edited that and now it does nothing even when selecting the sololeveling

**Comment by molar131** [comment]
completely deleted bot and tried again now i am getting this upon initial game creation:

[02/21/21 19:23:13] D2BS 3736: [ÿc1Errorÿc0 (22)] File(kolbot\libs\config\_customconfig.js:31) TypeError: configCheck[1].toString(...).substring(...).includes is not a function

**Comment by theBGuy** [comment]
whats your profile name and what's your setup tag?

**Comment by molar131** [comment]
I named the profile SCL-PAL and infotag is currently Hammerdin

**Comment by isid0re** [comment]
You need to use the kolbot from https://www.github.com/blizzhackers/kolbot the error you have is because you are using an unsupported install with sololeveling.
