### ISSUE TITLE
Bot made CTA and got rid of it

### ISSUE THREAD

**Issue by leocg** [isid0re/SoloLeveling#119]
Hi, my bot made a CTA during this night, but I notice the life was the same as before. I stopped the bot and launch a manual game, but didn't see the cta in second weapon slot (or anywere in stash, inventory or cube). 

[2021/02/23 03:01:12] <SCL-PAL> <Runeword Kept> (normal) Call to Arms (69) | Crystal Sword | 'AmnRalMalIstOhm' | One-Hand Damage: 18 to 55 | Durability: 11 of 20 | Required Strength: 43 | Required Level: 57 | Sword Class - Very Fast Attack Speed | +1 to All Skills | +40% Increased Attack Speed | +273% Enhanced Damage | Adds 5-30 fire damage | 7% Life stolen per hit | +2 to Battle Command | +2 to Battle Orders | +3 to Battle Cry | Prevent Monster Heal | Replenish Life +12 | 30% Better Chance of Getting Magic Items | Socketed (5)

It's normal (cause was a low roll) or there's something wrong with my configs?

**Comment by ciompek** [comment]
I think that runewords chekcing / using is broken. My bot keeps rolling spirits all the time, even after he got a perf one ;) Waste of runes ;(

**Comment by leocg** [comment]
Yeah, I figured it keep rolling runewords. The problem is that I don't have anything on second weapon slot and it didn't equip cta, just dumped it :( now i dont have a cta or runes lol! i'll start muling high runes and manually make/equip it. Thanks for the reply

**Comment by isid0re** [comment]
Tha is for posting this. This is the first I've heard of the bit not equipping the cta after making it. 

Have you made any changes to the class.config.js file? Or to the file sololeveling/functions/townoverrides.js? 

I appreciate any help you can provide. Thanks.

**Comment by leocg** [comment]
Thanks for the reply! I was using commit made yesterday when bot made CTA, all SoloLeveling files original without messing around. Don't recall making any changes on d2bot, but I can download again dev version and SoloLeveling last commit to see. Already found another OHM, so it's just a matter of time before making another one. Unfortunately I was sleeping when bot made runeword, so I don't know for sure what he do.. I'm equipped with a HOTO on weapon slot, maybe it compared stats with it and discard?

**Comment by isid0re** [comment]
I caught the mistake. It's an easy fix for you if you want to update it yourself or wait till I push the fix in a bit.

Go into sololeveling/functions/townoverrides.js

Go to the function town.towntasks
Move the line town.equipswap from after item.autoequip to before town.heal

Repeat the same edit in townoverrids.js for town.dochores

**Comment by leocg** [comment]
Thanks! Made the fix here, equipSWAP() now is below makeRunewords(), before heal().
