### ISSUE TITLE
Stop hitting Barrels

### ISSUE THREAD

**Issue by CafeRacer400** [isid0re/SoloLeveling#12]
Please remove the Barrels from hitting.

What would be good instead is open the graves on Tower (Countess) and just there... because often there will be 10fcr rings/amulet inside.

**Comment by isid0re** [comment]
The barrels and urns need to be kicked unless the pather code is rewritten to account for blocked paths causing walking bots to error out. 

I didnt consider adding the graves to the fix, but the rings and amulets are a good reason to add. Thanks
