### ISSUE TITLE
Item classification not working properly :(

### ISSUE THREAD

**Issue by ciompek** [isid0re/SoloLeveling#125]
Hi I found an issue regarding equipping items (i can provide screens later).

1. my soso found some nice boots - Tearhaunch that got tier 124.1 - Equipped - OK
2. she found some shitty rare boots with tier - 33.55 - Equipped - NOT OK
3. She found Sigons - 75.75 - OK

I also have observation - she started picking & equipping better staff once i uncommented kolton.nip

**Comment by isid0re** [comment]
Thanks. I will check into this as well.

**Comment by isid0re** [comment]
Pickit dynamic tiers and ntip all line up on logs. Weights updated. Closing issue.
