### ISSUE TITLE
Sorc Skipping all Diablo mobs

### ISSUE THREAD

**Issue by iKrazy** [isid0re/SoloLeveling#127]
Hey my sorc is still on the .leveling build, and seems to be skipping every single mob on the path to Diablo. This means she never actually gets to Diablo, and that means she never sees the seals. Keeps looping between getting stuck trying to skip every mob, and "Seal not found. Attempting portal trick". I didn't see anything in the immune section that would block her.

**Comment by isid0re** [comment]
Please try updating the files. There was an error in the sorc builds mixing the metorb attacks for the leveling build with the blizzballer buildfiles. So it wouldn't attack because it lacked the skills. 

Let me know if that corrected your problem. Thanks.

**Comment by iKrazy** [comment]
Hey thank you I updated the files, but still seeing the issue. It could be that my sorc's skills got misaligned vs the build, so I'm making a new one to test. I'll let you know

**Comment by iKrazy** [comment]
Working for me now thanks for the fix and the work on this!
