### ISSUE TITLE
Sorc not equipping Spirit Shield

### ISSUE THREAD

**Issue by zylo-** [isid0re/SoloLeveling#130]
Hi
My sorc isn't equipping Spirit Shield and doesn't seem like she has enough strength

How would I fix this?

These are the change's I've made to Sorceress.SoloLeveling.js

`//shield
			"[type] == shield && [flag] == runeword # [fcr] >= 30 # [tier] == 100000",
			"[name] == roundshield && [quality] == unique && [flag] != ethereal # [enhanceddefense] >= 180 # [tier] == 98000", //mosers
			"[Name] == GrimShield && [Quality] == Unique && [Flag] != Ethereal # [EnhancedDefense] >= 90 # [tier] == 99000",	
			"[type] == shield && ([Quality] >= Magic || [flag] == runeword) && [flag] != ethereal # [itemchargedskill] >= 0 # [tier] == tierscore(item)",
			//gloves
			"[name] == chaingloves && [quality] == unique && [flag] != ethereal # [itemmagicbonus] == 40 # [tier] == 100000", //chancies
			"[name] == chaingloves && [quality] == unique && [flag] != ethereal # [itemmagicbonus] >= 30 # [tier] == 99000", //chancies
			"[name] == lightgauntlets && [quality] == unique && [flag] != ethereal # [fcr] >= 20 # [tier] == 98000", //magefist
			"[Type] == Gloves && [Quality] >= Magic && [flag] != ethereal # [itemchargedskill] >= 0 # [tier] == tierscore(item)",
			//ammy
			"[name] == amulet && [quality] == set # [lightresist] == 33 # [tier] == 100000", //tals ammy
			"[Type] == Amulet && [Quality] >= Magic # [itemchargedskill] >= 0 # [tier] == tierscore(item)",
			//rings
			"[Type] == Ring && [Quality] >= Magic # [ItemMagicBonus] >= 40 # [tier] == 100000",
			"[Type] == Ring && [Quality] == Unique # [ItemMagicBonus] >= 30 # [tier] == 99000", //nagelring
			"[Type] == Ring && [Quality] == Unique # [itemmaxmanapercent] == 25 # [tier] == 98000", //soj
			"[Type] == Ring	&& [Quality] == Unique # [Dexterity] >= 20 # [tier] == 97000", //ravenfrost
			"[Type] == Ring && [Quality] >= Magic # [itemchargedskill] >= 0 # [tier] == tierscore(item)",`

**Comment by isid0re** [comment]
You will need to update the strength in the sololeveling buildfiles

**Comment by zylo-** [comment]
ok, but doesn't the sololeveling profile build that runeword? i think it should be default

**Comment by isid0re** [comment]
This is a work in progress and not a final product. So there are some leftover items as I'm testing out various builds and equipment and haven't set anything in stone.

Since I'm testing various things it doesnt make sense for me to cut things out and put them back in for each test I do.

**Comment by zylo-** [comment]
thank you, it's amazing! great work.
I just meant that I thought the sorc script was already building Spirit Monarch runeword so I thought it didn't make sense that the script wouldn't allocate str to equip it by default

**Comment by isid0re** [comment]
I appreciate the comments. Consider also using the discussions section here if you have questions. That way the issues doesnt get muddled. Thanks again.
