### ISSUE TITLE
Druid Dexterity

### ISSUE THREAD

**Issue by iKrazy** [isid0re/SoloLeveling#134]
Hey I slammed a HOTO onto my druid, but seems like the windbuild doesn't grab dex. Anything I should change on my side?

windbuild stats
["strength", 48], ["vitality", 165], ["strength", 61], ["vitality", 252], ["strength", 156], ["vitality", "all"]

**Comment by iKrazy** [comment]
slipped ["dexterity", 46], in the first set of stats, manually reset, and it seemed to pick it up correctly. Feel free to close just wanted to bring awareness

**Comment by isid0re** [comment]
Thanks for catching this.
