### ISSUE TITLE
Bot won't start due to Error in Config

### ISSUE THREAD

**Issue by cheguu** [isid0re/SoloLeveling#137]
![image](https://user-images.githubusercontent.com/79691487/109291851-c93ad380-7829-11eb-9ee1-969f625e067e.png)

Any Ideas what might be missing? I've set it up strict to the Plan.

**Comment by isid0re** [comment]
You have installed into a non supported repo or have customized your repo with non supported core files. You have to use the repo I link to in the instructions.
 https://www.github.com/blizzhackers/kolbot
