### ISSUE TITLE
Paladin & Raven Frost

### ISSUE THREAD

**Issue by iKrazy** [isid0re/SoloLeveling#138]
<level 60 hammerdin not wanting to keep Raven Frost he found equipped. https://i.imgur.com/xKJJxDa.png

Only thing I can think of would be the dynamic tier autoequip, but any ideas?

//rings
"[Type] == Ring && [Quality] >= Magic # [itemchargedskill] >= 0 # [tier] == tierscore(item)",

**Comment by theBGuy** [comment]
thank you for posting this. It's being worked on the issue is with how cannot be frozen is rated right now

**Comment by isid0re** [comment]
This has been patched.
