### ISSUE TITLE
Bot not finding seals on Diablo run

### ISSUE THREAD

**Issue by zkay27** [isid0re/SoloLeveling#14]
Error in SoloLeveling (sololeveling.js #1376) seal is undefined (Area: 108

**Comment by isid0re** [comment]
Thank you. I will look into what is causing the interaction error with the seals.

**Comment by zkay27** [comment]
I'm having more success with characters finding seals but I've found an additional issue. When my sorceress is successful in activating the seals she waits for Diablo to spawn and then throws a portal, goes to town, and exits the run and prints the "run completed" note to the console.

**Comment by isid0re** [comment]
Plus update to the latest character.config and sololeveling.js files.

I've changed the way I am handling diablo. This should prove to work better for you. Please let me know, thanks.

**Comment by zkay27** [comment]
seems to be solved! thanks!
