### ISSUE TITLE
Bot makes rws but never useses them

### ISSUE THREAD

**Issue by ciompek** [isid0re/SoloLeveling#142]
This is one annoying point - today treachery x2  and some insights - he made them and just dropped...

**Comment by isid0re** [comment]
The bot will make and upgrade gear. So it will remade certain runewords. The merc uses treachery and will keep upgrading it till it makes an eth treachery.  Same with insight it will keep making and upgrading till it makes an eth insight with full aura

**Comment by ciompek** [comment]
Only problem is that he makes those rws but not equips

niedz., 28 lut 2021, 03:58 użytkownik isid0re <notifications@github.com>
napisał:

**Comment by isid0re** [comment]
Hmm. If hes not equipping, that is a problem. I'll investigate thank you

**Comment by Almighty1g** [comment]
Thanks for looking into this! You are doing an incredible job. I too noticed this. For example today my Paladin made Ancients Pledge shield and did not equip it. Which is weird because its resistances are really poor in hell mode right now. Currently level 85.

**Comment by ciompek** [comment]
I got a really nice CTA he picked up :)

**Comment by Almighty1g** [comment]
Not sure if this helps to isolate the issue, but i have noticed the paladin i am leveling will make a spirit monarch (according to the bot events list) then doesnt equip it and either vendors or leaves it on the ground (not sure which i notice after the fact). This is in Hell difficulty that seems to be the problem for me. Using the Smiter build as InfoTag although its leveling as a hammerdin.

**Comment by isid0re** [comment]
Bot will level as a hammerdin till it gets key gear for a smiter to trigger the respec.
