### ISSUE TITLE
getPresetUnits failed, couldn't access the level!

### ISSUE THREAD

**Issue by jasonic143** [isid0re/SoloLeveling#145]
I've been running the bot on several characters and my Assassin encountered the following error repeatedly, preventing progression through Act 1.

_Error in SoloLeveling (pather.js #1337) getPresetUnits failed, couldn't access the level! (Area: 31, Ping:16, Game: )_

I was able to get around the issue by editing my save file and adding the 'Inner Cloister' waypoint, so the issue was potentially caused by attempting to use the Inner Cloister waypoint before it had been discovered.

**Comment by isid0re** [comment]
Hi,

Are you playing on singleplayer? I ask because that is a known singleplayer bug in kolbot.

**Comment by jasonic143** [comment]
> Hi,
> 
> Are you playing on singleplayer? I ask because that is a known singleplayer bug in kolbot.

Hi, yes this was in singleplayer.

Do you know what triggers the issue to occur? I've not had it happen on other characters.

Also is there any workaround other than getting the waypoint before resuming the bot?

Thanks

**Comment by isid0re** [comment]
Its map seed related. I was trying the portal trick (like I did with diablo) to try and fix it but unfortunately that didnt work. If you you select tcp instead of singleplayer it will reroll maps for you so it's less of an issue.

**Comment by jasonic143** [comment]
> Its map seed related. I was trying the portal trick (like I did with diablo) to try and fix it but unfortunately that didnt work.
> 
> If you you select host tcp instead of singleplayer in the game mode on the profile it will reroll maps for you so it's less of an issue.

Ah okay I'll use Host TCP in future, thanks for letting me know!
