### ISSUE TITLE
Breaking in A4 Normal

### ISSUE THREAD

**Issue by iKrazy** [isid0re/SoloLeveling#147]
Hey I have seen two new characters reach A4 normal, then they start grinding towards Diablo. Somewhere in the middle, and maybe even after killing Diablo, they are getting stuck in town. They'll login, walk to Tyrael, then start "Stalling" and logout. Then they're stuck in the loop of logging in, walking to Tyrael, and "Stalling".

**Comment by isid0re** [comment]
Thanks. That sounds like its killed diablo but somehow didnt take the portal to act 5 and is now bugging. Can you manually take the tirael portal to act 5 and see if that fixed it.

**Comment by iKrazy** [comment]
I don't think chars created through SoloLeveling are set as Expansion chars, but I can't find anything in the files to verify that. I converted one of them, and I'm watching it now.

**Comment by iKrazy** [comment]
After converting and manually going to A5 it is working for me.

**Comment by theBGuy** [comment]
what was your profile name?

**Comment by iKrazy** [comment]
Oop good catch I named them incorrectly. Thank you both
