### ISSUE TITLE
Bot tries to sell Hellforge Hammer which returns "Your Connection Has Been Interrupted" screen

### ISSUE THREAD

**Issue by zkay27** [isid0re/SoloLeveling#15]
Bot then just sits on the home screen and seems to wait forever. 

Is it possible to add a function that restarts the bot on unexpected exits?

**Comment by isid0re** [comment]
Thank you for posting this bug. It has been corrected. Please update to the most recent version in the repository.

**Comment by zkay27** [comment]
I'm still running in to this issue even after updating.  Could it be that the Hellforge Hammer needs to be added to the questItem array on line 27 of SoloLeveling.js ?

**Comment by isid0re** [comment]
Well the hellforge hammer quest has been fixed. There is an issue with taking the diablo portal to act 5. It will be corrected later today.

**Comment by zkay27** [comment]
I figured out my issue. The character picked up the hammer in a previous game before I implemented your update and the bot didn't know what to do with the extra hammer. Thanks!

**Comment by isid0re** [comment]
Just to let you know the revised code will stash the old hammer before doing chores. This prevents a connection interrupted. After the chores it will drop the old hammer then proceed to start questing
