### ISSUE TITLE
Error in leveling

### ISSUE THREAD

**Issue by Xizbox** [isid0re/SoloLeveling#150]
D2BS ;; Starting default.dbj
D2BS ;; default.dbj running
[Error (22)] File(kolbot\libs\config\_customconfig.js:19) TypeError: configCheck[1].toString(...).substring(...).includes is not a function
Loaded NIP: kolton.nip. Lines: 813. Valid entries: 338. Time 16 ms
Loaded NIP: LLD.nip. Lines: 426. Valid entries: 169. Time: 15 ms
Starting script: Mausoleum
Start ToolsThread script
[Error (22)] File(kolbot\libs\config\_customconfig.js:19) TypeError: configCheck[1].toString(...).substring(...).includes is not a function
Script default.dbj ended

(Fresh level 1 sorceress with d2bot profile name SCL-SORC and info tag Blizzard
It just passes all monsters running to mausoleum, gets low hp, chickens out, rinse repeat

**Comment by theBGuy** [comment]
are you using the blizzhackers repo?

**Comment by Xizbox** [comment]
> 
> 
> are you using the blizzhackers repo?

No, just googled and followed the guide on: https://diabloculture.com/pages/kolton-bot

**Comment by theBGuy** [comment]
https://github.com/blizzhackers/kolbot.git

use this repo

**Comment by Xizbox** [comment]
Absolute god. tyvm!
