### ISSUE TITLE
Bot Only Utilizing 1 Ring Slot

### ISSUE THREAD

**Issue by Almighty1g** [isid0re/SoloLeveling#157]
Hello! I noticed that the bot will only equip items to one ring slot instead of two. The other slot always sits empty. Besides being an incredibly obvious give away that blizzard could use to detect bots, it also lessens the power level of the character, especially if its missing some resistances.

If its something i am doing wrong i apologize but i noticed this was happening on every character i made.

I also just wanted to say I donated a few days ago because I really appreciate your work. Hope you keep going and even continue in D2R if possible!

**Comment by isid0re** [comment]
Thanks for your support. I also saw the single ring problem.  commented about it in the discussions yesterday before I put a hotfix out for the single ring in the last push. Please update your files.  And thanks again.

**Comment by Almighty1g** [comment]
> Thanks for your support. I also saw the single ring problem. commented about it in the discussions yesterday before I put a hotfix out for the single ring in the last push. Please update your files. And thanks again.

Thanks! Updated my files.
