### ISSUE TITLE
Merc cannot automatically runewoed Ethereal's armor

### ISSUE THREAD

**Issue by ircopdd** [isid0re/SoloLeveling#16]
My chest has defense 1140 Ethereal's armor but he chooses runewoed Superior armor

for Treachery runewoed

**Comment by isid0re** [comment]
What was the ethereal runeword base you were using?

**Comment by ircopdd** [comment]
> What was the ethereal armor base you were using?

Archon Plate (85)
Defense: 1140
Durability: 31 of 31
Required Strength: 93
Required Level: 63
Ethereal (Cannot be Repaired), Socketed (3)

**Comment by ircopdd** [comment]
Find the problem. 

Runeword will only be performed if chest has two 3 Socketed armors.
