### ISSUE TITLE
Error (22)

### ISSUE THREAD

**Issue by Vangha77** [isid0re/SoloLeveling#163]
Hey,

i got the following error:
[Error(22)] File(kolbot\libs\config\_customconfig.js:31) TypeError:configCheck[1].toString(...).substring(...).includes is not a function

I installed the newest revo, to make sure that isnt why the error accures.

**Comment by Vangha77** [comment]
Tried to do it again and installed newest revo without any other profiles, now i got this:

[Script Warning (162)] File(kolbot\libs\config_customconfig.js:31) reference to undefined property configCheck[1]
[Error(22)] File(kolbot\libs\config_customconfig.js:31) TypeError:configCheck[1] is undefined

**Comment by isid0re** [comment]
Sounds like you had a typo or extra space in your info tag.
