### ISSUE TITLE
bot doesnt sell automatically

### ISSUE THREAD

**Issue by danteafk** [isid0re/SoloLeveling#169]
heya, my sorcs just run around with full inventory and do not sell anything, what can I do?

**Comment by unsk0326** [comment]
My sorcs are running well, I run it from yesterday. 
How about read readme or codes under config?

**Comment by isid0re** [comment]
First make sure you are using the right kolbot repo. https://www.github.com/blizzzhackers.com/kolbot 

Secondly,  if you are using this on a modded private server then the servers unit codes have possibly changed and kolbot/sololeveling wont work properly
