### ISSUE TITLE
wrong resist calc

### ISSUE THREAD

**Issue by unsk0326** [isid0re/SoloLeveling#170]
Sololeveling code has wrong resist value. 
Cr might be 43, lr is 41?

frRes = Math.min(75, me.getStat(39) - resPenalty);
crRes = Math.min(75, me.getStat(41) - resPenalty);
lrRes = Math.min(75, me.getStat(43) - resPenalty);
prRes = Math.min(75, me.getStat(45) - resPenalty);

btw thanks for your code. 
It's really happy when I see it works.

**Comment by isid0re** [comment]
Thank you. I will update the starter script to correct that mistake.

**Comment by unsk0326** [comment]
Logic was ok. Only updateStatus value was wrong.  
lol
