### ISSUE TITLE
Stuck at beginning of act 5

### ISSUE THREAD

**Issue by dreyda** [isid0re/SoloLeveling#173]
Error in SoloLeveling (sololeveling.js #88) this[sequence[k]] is not a function 

I began running a paladin (Hammerdin) from level 1 and it has gotten to act 5 normal.  It kills Diablo, then as soon as it takes the portal to act 5, it gets the error above.  It then leaves the game, creates a new game, does its town sequence in act 5, then goes back to the River of Flame, runs Chaos Sanctuary, kills Diablo, takes the portal to act 5, gets the error above and continuously repeats this process.

I did a fresh install of kolbot last night as well as installed the SoloLeveling files last night.

Thanks for any help that can be provided.

**Comment by ciompek** [comment]
I have exactly the same problem

**Comment by Abbadon89** [comment]
quick workaround.
SoloLeveling-master\libs\bots\SoloLeveling.js

i commented sequence like this and bot run act 5

![image](https://user-images.githubusercontent.com/26330104/112746627-4768d200-8fb0-11eb-9b91-ef76c52a38c0.png)

**Comment by dreyda** [comment]
Thanks Abbadon!

I commented out shenk and savebarby quests and it's running fine now.  I'll just pop on and do those quests manually later.

**Comment by Abbadon89** [comment]
I see that problem is only on normal, bot runs nm without problem

**Comment by isid0re** [comment]
Bot has been updated to correct the error. 

A hotfix if you dont want to update at this time is:
open sololeveling/scripts/savebarby.js
Go to line 7
Change 'saveBarby' to 'savebarby'

**Comment by dreyda** [comment]
Thanks isid!

I appreciate the quick fix on this!
