### ISSUE TITLE
Common for constant death a1?

### ISSUE THREAD

**Issue by shokkakhan** [isid0re/SoloLeveling#176]
I have a Blizzard Sorc being built by SoloLeveling. In the last hour, it has only reached level 3 because my Sorc keeps running out of mana, attacking with staff and then nearing death and Chickening out of the game. Is this normal for the first  few levels? Or is something wrong?

**Comment by isid0re** [comment]
That doesnt seem right. I'll take a look and see what's going on. Thank you.

**Comment by shokkakhan** [comment]
After around lvl7 or so, things have appeared to start going a little smoother.. I wonder if it was really bad RNG, and not finding any pots, or good gear while leveling?

**Comment by shokkakhan** [comment]
So, right now, its been about 14 total hours on this char: Blizzard Sorc, lvl 24, hasnt defeated Mephisto yet, still on normal, gear is looking very low tier. Bot keeps randomly dropping from games and making new game, without posting anything to D2BS console, then rerunning Travincial, and attempting Mephisto, before randomly dropping without message. I dont know how many times it has repeated this cycle, as I have been at work. Will update when more information is available.

**Comment by shokkakhan** [comment]
`[03/30/21 15:26:05] D2BS 9264: [Strict Warning] Code(162) File(c:\users\shokkatweej\desktop\kolbot-master\d2bs\kolbot\libs\sololeveling\functions\patheroverrides.js:484) reference to undefined property unit.type
Line: (null)
[03/30/21 15:26:05] D2BS 9264: [ÿc9Strict Warningÿc0 (162)] File(kolbot\libs\sololeveling\functions\patheroverrides.js:484) reference to undefined property unit.type`


In checking the logs, I receive this error everytime I enter travincial, but that is really the only error I am seeing.

Before the game decides to end randomly, I am seeing the following in the logs:
`[03/30/21 15:41:37] D2BS 9264: ÿc2Drinking potion from inventory.
[03/30/21 15:41:39] D2BS 9264: Script default.dbj ended
[03/30/21 15:41:42] D2BS 9264: Script tools\autobuildthread.js ended
[03/30/21 15:41:42] D2BS 9264: Script tools\townchicken.js ended`

**Comment by shokkakhan** [comment]
And now that I am sitting here keeping an eye on the bot, it appears that the bot is pretty consistently running itself into the middle of larger groups in order to engage in a fight, instead of fighting them from a distance, which I would assume to be the best option for Sorc's considering how soft they are.

**Comment by isid0re** [comment]
Movement on the bot is still in the works as I test various changes across the classes.

**Comment by shokkakhan** [comment]
Bot is now attempting to Chaos//Diablo at level 25, after finally succeeding in a Mephisto run. Bot is chickening pretty quickly after entering River of Flame on its way to Chaos Sanctuary... causing a couple hundred second "min game wait" timeout in D2BS.

As much as I am harking on all of this, I gotta say this is all very impressive man, and I appreciate the work you have put into all of this. Keep it up! For real, this is huge!!!
