### ISSUE TITLE
PD2 Issue Spirit Sword / Shield 

### ISSUE THREAD

**Issue by jibby1445** [isid0re/SoloLeveling#184]
Bot does not pickup runes for Spirit Shield / Sword in PD2

I Attempted to pickup Amn Rune for the bot myself, it sold it to the vendor. 

a 4 socket sword is in the bank though, so part of the script is working. 

Another User on discord had the same issue so it is not just me.

**Comment by isid0re** [comment]
Pd2 runes have a different classid will be dealt with in pd2 integration
