### ISSUE TITLE
Feature Request PD2 Sequence Fix

### ISSUE THREAD

**Issue by jibby1445** [isid0re/SoloLeveling#185]
Bot will continue to run sequence quests even if they are already complete if it chickens.

EX. Bot has completed Act 1,2,3 but chickens in act 4 diablo. It will reload the game and run all of the quests for Acts 1,2,3 until it gets back to Diablo. 

**Solution:** Would be nice for bot to know that is has already completed these quests and can go straight to diablo to try again.

**Comment by isid0re** [comment]
Bot reruns certain quests based on globals.js check task.  If the criteria is met it will not run
