### ISSUE TITLE
Feature Request PD2 **Lesser Hydra (level 12) - Hydra (Level 30) Leveling Build ** 

### ISSUE THREAD

**Issue by jibby1445** [isid0re/SoloLeveling#186]
Would be nice to use Lesser Hydra & Hydra for PD2 Starter build & Final Build, these skills are very strong and would make the bot a lot stronger. 

Please and thank you, if it doesn't make sense no worries thank you for your efforts!!

**Comment by isid0re** [comment]
You can adjust the build files themselves to do this.
