### ISSUE TITLE
Stuck on Summoner (red teleport pads) (classic)

### ISSUE THREAD

**Issue by CafeRacer400** [isid0re/SoloLeveling#19]
The bot seems to cannot use the red teleport pads on the arcaine map towards summoner. 
He makes tp in front of it and says summoner failed.

![summoner](https://user-images.githubusercontent.com/73992962/100421549-df00f700-3088-11eb-9285-e02a77c4e21b.png)

**Comment by isid0re** [comment]
next time this error happens can you please take note of the following:
1 which direction (N,S,E,W) the bot is heading
2 how many many attempts it used before failing
3 classic/expansion (from your earlier findings I'm presuming classic) 
4 character type

this will help to debug what happened. thanks.

**Comment by isid0re** [comment]
I have been unable to replicate the report. Closing.
