### ISSUE TITLE
area id's

### ISSUE THREAD

**Issue by loko316** [isid0re/SoloLeveling#194]
got everything to run for the sololeveling but when it goes to do quest it tries to take wps and i get errors like 

Error in Corpsefire (pather.js line 1458): getPresetUnits failed, couldn't access the level!

so i went and gave toon all wps thinking that was a issue but i still get errors when i try to run.

**Comment by isid0re** [comment]
Are you playing vanilla d2 or pd2?

**Comment by loko316** [comment]
pd2

**Comment by isid0re** [comment]
You need to update your preset ids.
