### ISSUE TITLE
act 3 bug

### ISSUE THREAD

**Issue by oambra** [isid0re/SoloLeveling#195]
when going to lower kurass
  Error in SoloLeveling (templeruns.js #26) me.area is not a function (Area: 79, Ping:422, Game: 456791)

**Comment by Kalradia** [comment]
I made a quick fix for this, until he commits a fix himself. If you open your kolbot folder, then go into d2bs\kolbot\libs\SoloLeveling\Scripts and open the templeruns.js script, find line 26 and replace it with this:

`if (me.area == 94 && !Quest.Status("lamessen")) {`

That should get the bot functioning correctly and remove the error.

**Comment by isid0re** [comment]
> I made a quick fix for this, until he commits a fix himself. If you open your kolbot folder, then go into d2bs\kolbot\libs\SoloLeveling\Scripts and open the templeruns.js script, find line 26 and replace it with this:
> 
> `if (me.area == 94 && !Quest.Status("lamessen")) {`
> 
> That should get the bot functioning correctly and remove the error.

Thanks for catching that. I kinda feel silly doing me.area(94) I'll update shortly
