### ISSUE TITLE
Some question 

### ISSUE THREAD

**Issue by Otodragon** [isid0re/SoloLeveling#202]
Hi.
It's nice project man!

I just start 2 Sorc one in CL and 1 in LOD 
When the char die he don't resuscitate. Can I do so ajust for that?
I want setup the chicken and other thing but I don't found the char. Config.. 
This file exist?

Thank for your time!

**Comment by Otodragon** [comment]
Some news

After change my game language (Fr to En) the bot revive after death.
After 9 h of botting 
Ladder Sorc - - lvl25 act 3
Classic sor lvl 20 act 2 (block in Viper temple. Try to kill all snake a lvl 2 when just need to télé on the hostel) some fix maybe?
Against time : nice work

**Comment by isid0re** [comment]
Please update to the most recent push. I've been fixing problems in the script. And testing new build options for speed. The sorceress is currently being tested for using a quick teleport access.

**Comment by Otodragon** [comment]
Thanks for answer.
I use the last version kolbot+solo leveling (install yesterday night) have you make new version this night?
I have config the 2 Sorc with blizzball but she use bolt. That normal? Witch level she respel?

**Comment by Otodragon** [comment]
Attention après maj de global. JS(6 hours ago) 
Bot act 3 prepare le script et plante..
I keep my last file and that works again. 

See other thing 
Sorc classic blok in maggot lair. She go lvl 3 but make TP before kepping staff and restart the run and take way point. Finally after 5 try she take the staff 🤗
I think classic Sorc not optimisés for don't use merc🤔


Sorc LOD. Act 3 can't go sewer lvl 2 using télékinési need manual click.

**Comment by isid0re** [comment]
I just pushed the pather.useunit fix addressing this problem. It's been confirmed fixed
