### ISSUE TITLE
Starter. JS sorcess 

### ISSUE THREAD

**Issue by Otodragon** [isid0re/SoloLeveling#203]
Hi again

I would like change the setup for starter. 
I want my sorcess use firebolt and fire ball 
Nova is very dangerous (too much chiken inside mob) and light bolt not really effective.
What file I need to change.
If you can explain me, I will do the change and share my file here. 

PS: previous updrage work fine
Congrats!

**Comment by isid0re** [comment]
Please post your question in the discussion area. This is for bot bugs and issues.
