### ISSUE TITLE
Why does bot keep doing Countess/Andy over and over again??

### ISSUE THREAD

**Issue by JediPeaceFrog** [isid0re/SoloLeveling#217]
Hello.  Just curious as to why the bot keeps going back to act1 whenever it finishes an act?  it finishes act 2, goes back to Countess/Andy.  Finishes act 3, creates new game and starts all the way back on Countess/Andy??   been running bot for 36 hours straight...its at level 48 and in act 3 nightmare.   if it didn't keep going back after every act, should be in hell baal by now.   anyway just curious if its something I did/didn't do.

**Comment by isid0re** [comment]
If you are referring to the the start of each run then yes it does run countess and andy in nightmare and hell. It does so for runes and jewelry. 

Also, please use either the discussion area on github or the discord for questions. This wasnt a bug/issue. Thanks.
