### ISSUE TITLE
This is getting embarrassing to watch...

### ISSUE THREAD

**Issue by JediPeaceFrog** [isid0re/SoloLeveling#218]
No offense, bro. a nd I do appreciate the time and effort...but this latest update adding the druid and assassin is just not right.  your first one was great...was in hell in 15 hours.  this one still in nightmare after 36 hours and does nothing now but keep re-starting games and going back to countess/andy/trav.  over and over. and over and over.   you need to pull this and go through it again.

**Comment by isid0re** [comment]
Im not offended. I have a list of things I'm working on in the bot. There is no team of developers I'm just 1 guy making a script in his spare time. Who has never taken a coding course/lesson in his life. 

I'm learning as I build it. Even though I made this a public repo I am not doing this for anyone but myself. So my wants and focus may not align with others.  

I do appreciate people posting thoughts and discussions to improve the bot.  I always consider what people post and propose and if it fits with my project vision.

Again thanks for using the script and posting.
