### ISSUE TITLE
PD2 Act 3 First Quest Goblin Figure.

### ISSUE THREAD

**Issue by Greenapple2021** [isid0re/SoloLeveling#224]
Will be nice if you add it to Quest list in solo lvling.
Ever more life always.

**Comment by Wullff91** [comment]
got this in normal d2 too

**Comment by isid0re** [comment]
If you are referring to the jade figurine quest, then that is already included.

**Comment by Wullff91** [comment]
yeah but he isn't speaking to cain, it doesnt work well. check it later.
