### ISSUE TITLE
Bone shield (Nec) Precast !!!

### ISSUE THREAD

**Issue by Greenapple2021** [isid0re/SoloLeveling#226]
Watching my second Nec after xx hours, bone shield should be much better precasting after step 1/3 or gone direct precast but he didn't make that. 
Sometimes after sec or mins or dead.

**Comment by isid0re** [comment]
After attack controls when precast is handled during an attack sequence.

**Comment by Greenapple2021** [comment]
He is running ,summon army attack but he took hits shields gone and didn't make precast if its gone.
