### ISSUE TITLE
Sorc doesn't cast skills, keeps going back to Act4

### ISSUE THREAD

**Issue by juliuscrn** [isid0re/SoloLeveling#227]
See title. my sorc seems to be standing still and killing things with frost shield. It also tps and goes back to act 4 to talk with vendors a lot, and I don't understand why. Any advice?

**Comment by iriFiri** [comment]
Pd2 issue, use discord /close

**Comment by juliuscrn** [comment]
I don't think so, this is battle.net.

**Comment by iriFiri** [comment]
Ask for help in discord
