### ISSUE TITLE
Act 3 quest 1 doesnt work.

### ISSUE THREAD

**Issue by Wullff91** [isid0re/SoloLeveling#228]
When he got the figure he run to meshif and afterwarts to alkor but doesnt talk to cain so he wont get the quest done.

**Comment by isid0re** [comment]
Quest is done when he drinks the potion. I've added prints on the quest status during the stages and it registers complete after receiving the potion from Alkor. 

So I'm not sure what you mean by it not showing complete if you dont talk to cain. Could you further explain. Thanks

**Comment by Wullff91** [comment]
I saw it when he got the item.
He does run to meshif and then to alkor and cannot finish the quest because he doesnt talk to cain first.
my 2 sorcs do not fineshed the quest until now.

**Comment by aim2kill** [comment]
Give the bot time he will get it complete, btw you dont need 2 talk to cain at all to finish the quest

**Comment by Wullff91** [comment]
Still unfinished :)

**Comment by isid0re** [comment]
i just noticed this today. I looked over about 5 characters and saw you were right. 3 were missing the quest. So i'm going to look more into it. and change the approach some. thanks.

**Comment by Greenapple2021** [comment]
Yes is true.

**Comment by isid0re** [comment]
Updated tested confirmed fixed
