### ISSUE TITLE
Sorc (meteorb 88lvl) keep dying

### ISSUE THREAD

**Issue by Chaser00** [isid0re/SoloLeveling#233]
It's a couple of days that my sorc after reached lvl 88 keep dying trying to kill ancients in act 5, she also die randomly during games, seems unable to chicken out before, there's a way to stop progress until some specific stats are reached or at least fine tuning the chicken method?

**Comment by isid0re** [comment]
The random exits are something I've seen and am debugging a cause so I can create a solution.
