### ISSUE TITLE
Sorc stuck on normal Diablo sequence due to no gold

### ISSUE THREAD

**Issue by woodske** [isid0re/SoloLeveling#235]
![image](https://user-images.githubusercontent.com/20936822/117191421-6455a980-ad95-11eb-9ed9-bb9333ad44fd.png)
![image](https://user-images.githubusercontent.com/20936822/117191483-76cfe300-ad95-11eb-9b0b-97243afa5f6f.png)

My sorc got stuck in normal trying to run the diablo sequence because she had no gold. She couldn't afford any pots and would go to river of flame then almost immediately die. I started 6 sorcs at the same time and you can see from the screenshot she is under leveled and has spent half of the runtime out of game.

I have a fix where the tombs sequence is added if the character has less gold than the LowGold config. She was able to revive merc and fill her pots this way and proceed to chaos sanctuary. I tried running pits at first, but that wasn't generating enough gold. Ancient tunnels could be another good option, but I haven't tried it.

Let me know what you think and I can make a PR if it's sufficient.

```
case "tombs": //tombs
    if ((Pather.accessToAct(2) && me.normal && me.charlvl < 25) || (Pather.accessToAct(2) && me.gold < Config.LowGold)) { // farm tombs if low gold
        SetUp.sequences.push("tombs");
    }
```

**Comment by isid0re** [comment]
I actually had something similar prior, but I found it would add on an excessive amount of time. So I've been looking for another approach that wont take too much time. I'll look into tomb runs again. Also I have a lowgold function that exists using certain gold caps instead of config.lowgold.
