### ISSUE TITLE
Stuck at 89, continue to die

### ISSUE THREAD

**Issue by Chaser00** [isid0re/SoloLeveling#237]
![image](https://user-images.githubusercontent.com/82617543/117578058-d529f800-b0ec-11eb-954d-844598a15dfa.png)
Here's the console, how can I post logs, and where I found them, to see what happened?
She reach 40, 50% of level then die dropping again at 5%, this behaviour occour since she hits 89

**Comment by isid0re** [comment]
Go to the sololeveling/data folder and look at the last script completed the next script in sequence is the one its dying on. Or alternatively you can open the d2bs log and look for the last script printed before the game closes.
