### ISSUE TITLE
Treachery for merc

### ISSUE THREAD

**Issue by Wullff91** [isid0re/SoloLeveling#239]
The Bot doesnt make that runeword until now.
Sorc aswell Paladin and they are lvl 92/93.
All got lem and other rune for it.
And my paladin got runes for enigma for 3 days and didnt find any armor for it or didnt even pickup for a roll.

**Comment by isid0re** [comment]
There was a small error in the configs for treachery on the merc. It's been corrected. And should build and equip now

**Comment by Wullff91** [comment]
Already insiert this update in my files but does not help

**Comment by isid0re** [comment]
Ok i will reopen and investigate thanks.
