### ISSUE TITLE
Barbarian Warcry PrecastOverrides.JS Causes Stuttering

### ISSUE THREAD

**Issue by iRatePiRat3** [isid0re/SoloLeveling#240]
Barbarian will walk very slowly in place tile per tile after shout. Almost seems like lag, However i found that adding a delay to each precast and casting again solves the issue.

case 4: // Barbarian - TODO: BO duration
		 if (!me.getState(32) || !me.getState(51) || !me.getState(26) || force) {
			var swap = me.weaponswitch;

			Attack.weaponSwitch(this.getBetterSlot(149));

			if (me.getSkill(155, 0) && (!me.getState(51) || force)) {
				Skill.cast(155, 0); // Battle Command
				delay(me.ping + 100);
				Skill.cast(155, 0); // Cast twice. It works on itself

			}

			if (me.getSkill(149, 0) && (!me.getState(32) || force)) {
				Skill.cast(149, 0); // Battle Orders
				delay(me.ping + 100);
				Skill.cast(149, 0); // Battle Orders
			}

			if (me.getSkill(138, 0) && (!me.getState(26) || force)) {
				Skill.cast(138, 0); // Shout
				delay(me.ping + 100);
				Skill.cast(138, 0); // Shout
			}
		
				Attack.weaponSwitch(swap);
		}
		
		break;

**Comment by theBGuy** [comment]
Check my Precast pr, try that instead

**Comment by iRatePiRat3** [comment]
@theBGuy Does not fix
