### ISSUE TITLE
Developer Undefined

### ISSUE THREAD

**Issue by NightWolf-04** [isid0re/SoloLeveling#245]
hey! i followed everything in the walkthrough to a T, but when i launch the bot, i get "Developer Undefined" as the error. is there something i need to do to fix this? (im fairly new to Txt based botting, so help in lehman terms would be appreciated)

**Comment by isid0re** [comment]
It sounds as a bad install. 

Verify your libs/config/_customconfig.js and your default.dbj  in the kolbot directory match the ones hosted here. 

You need to overwrite those 2 files. When you copy them into the kolbot folder

**Comment by NightWolf-04** [comment]
great! so i fixed the Library issue. sorry, i saw the arrows on the picture, and got confused, and only transferred those two files. ^.^'' thanks. 

new error arose however.  this time, ill screenshot and ad it for you. :D

![11](https://user-images.githubusercontent.com/84468657/119917706-10be2200-bf35-11eb-818a-98076841e435.PNG)

**Comment by isid0re** [comment]
Well the `...is not a function` error is because you are using the wrong kolbot. Download the version link from the one in my instructions.

**Comment by NightWolf-04** [comment]
oh! i thought it was all the same, and this just edited the original. 

Sorry, total noobie when it comes to this. you have been super helpful.  ill give that a go and see what happens

Keep ya posted!

**Comment by NightWolf-04** [comment]
alright!  its up and running! seems to be doing its thing! thanks so much for the help! sorry to waste your time with nooby questions from a 1st time botter. :D 

Very much appreciated!
