### ISSUE TITLE
bug: can't go to nightmare

### ISSUE THREAD

**Issue by ircopdd** [isid0re/SoloLeveling#25]
After creating the room, exit the game immediately and display SoloLeveling: run completed. Character Level: 24. Running script again!

The error seems to have come from Attack.js

This problem only occurs in sorc

**Comment by isid0re** [comment]
The script had been updated to include the attack.js file. That was what caused the error Attack undefined. Please update your files to fix.

Regarding the error you are having about not entering nightmare. Please check your profile settings that the difficulty setting is "highest" and not "hell".

**Comment by ircopdd** [comment]
difficulty setting is "highest" 

![Ashampoo_Snap_2020年12月6日_01h59m38s_005_](https://user-images.githubusercontent.com/3633003/101259922-fca81d80-3766-11eb-9868-73a2d6d35ded.png)

**Comment by ircopdd** [comment]
[](https://youtu.be/VRKbh9Q2Or4)

**Comment by ircopdd** [comment]
> 該腳本已更新為包括Attack.js文件。這就是導致錯誤“未定義攻擊”的原因。請更新您的文件以進行修復。
> 
> 關於錯誤，您即將進入噩夢。請檢查您的個人資料設置，難度設置為“最高”而不是“地獄”。

https://youtu.be/VRKbh9Q2Or4

i make video

**Comment by isid0re** [comment]
Thank you. I had someone else report the same issue with paladin. I will investigate this and find a solution soon. Thanks

**Comment by isid0re** [comment]
Just worked thru the solution with another person who had the same problem.  The cause is the bit completed the quest but did not take the red portal. I will fix the script, but you can fix the problem manually for now by having the bot go thru the red portal to act 4.  Thanks again for your help.
