### ISSUE TITLE
Act 4 tyrael quest

### ISSUE THREAD

**Issue by Sheep30** [isid0re/SoloLeveling#255]
Hammerdin is trying to kill Tyrael once it's dead but comeback as a spirit. I saw it in Nightmare.
Also he doesn't open pit lvl 2 chest. I saw it in nightmare.

**Comment by isid0re** [comment]
I've done some updates for chests. Should fix the pits 2. 

Seems like something glitched eith hammerdin. I'm going to close this and keep tabs if this happens again. 

Thanks.
