### ISSUE TITLE
Necro - PSN

### ISSUE THREAD

**Issue by CodeNoobie17** [isid0re/SoloLeveling#258]
Good Afternoon,

First I want to thank you guys for keeping this going and maintaining it.

Act 2 - Necro will spam amp damage on mummy sarcophagus without attacking it causing it to drain mana before it skips usually dies due to it being spam locked.

**Comment by isid0re** [comment]
thanks, the necro isCursable function in stock kolbot is incomplete and I've been adding to the list. I will add this one as well.
