### ISSUE TITLE
ntipoverrides.js(line39): arraytoloop is undefined

### ISSUE THREAD

**Issue by Emmes91** [isid0re/SoloLeveling#261]
The bot has worked perfect until level 28 when it reset all stats and stands in act 4 and makes this error message

 ntipoverrides.js(line39): arraytoloop is undefined
[error (o)] File(Kolbot\libs\common\config.js:95) Error: config.init: Error in character config.
-------------------------------

NTIP.arrayLooping = function (arraytoloop) {
	for (let q = 0; q < arraytoloop.length; q += 1) {
		NTIP.addLine(arraytoloop[q]);
	}

	return true;
};
--------------------------------------------------
Runing 1 bot leveling a cold sorc

regards

**Comment by isid0re** [comment]
How old is the sololeveling version you are running?

**Comment by Emmes91** [comment]
I deleted sololeveling and installed the latest and it didnt make any diffrence but when i downloaded another kolbot version then it worked =)
Regards

**Comment by isid0re** [comment]
What is the link to the kolbot version you downloaded?

**Comment by Emmes91** [comment]
Kolbot

https://github.com/blizzhackers/kolbot.git

and the Solo leveling is 

https://github.com/isid0re/SoloLeveling

**Comment by isid0re** [comment]
Ok, thanks. This is the kolbot listed on my repo to use.

**Comment by InsomniakSam** [comment]
Hey i have the same issue have downloaded both link in the readme.
d2bot 20.6.7.100 

still have the error 

ntipoverrides.js(line39): arraytoloop is undefined
[error (o)] File(Kolbot\libs\common\config.js:95) Error: config.init: Error in character config.

have a sorc cold and a bow zon both have the error while switching config from normal to nm

**Comment by Emmes91** [comment]
Same problem accured when trying to do a javazon.

**Comment by isid0re** [comment]
A few people commented in discord with the same problem. I've been investigating and have isolated a potential cause and will be testing a fix today.

**Comment by isid0re** [comment]
discord confirmed the fix of the error. pushed the fixed files.
