### ISSUE TITLE
slow walking bug

### ISSUE THREAD

**Issue by Axion123** [isid0re/SoloLeveling#265]
I have the problem, that from time to time my char is slow moving?

It is not a ping problem.. btw. char is not frozen or have any other negative effect on it.

Is there any fix? Any solution?

**Comment by theBGuy** [comment]
that is a d2bs bug, solution is start a new game

**Comment by Axion123** [comment]
i do it allready, but it comes back :(

**Comment by isid0re** [comment]
As previously stated, this is a core exe bug of d2bs/kolbot and not something that can be fixed in javascript. 

Closing issue.
