### ISSUE TITLE
Error.init:

### ISSUE THREAD

**Issue by DeMoN100** [isid0re/SoloLeveling#270]
Error.init: Error in character config. Config.Hephasto is undefined in all character configs.

Referring to this line exactly!
```
Scripts.Hephasto = false;
	Config.Hephasto.ClearRiver = false; // Clear river after killing Hephasto
	Config.Hephasto.ClearType = 0xF; // 0xF = skip normal, 0x7 = champions/bosses, 0 = all
```

**Comment by isid0re** [comment]
You are using the wrong kolbot download. Follow the readme instructions and use the download link listed.
