### ISSUE TITLE
Error(1)default.dbj

### ISSUE THREAD

**Issue by DeMoN100** [isid0re/SoloLeveling#272]
I have replaced the default.dbj with yours and got this error on startup.

default.dbj:184 Reference error SetUp is not Defined

**Comment by theBGuy** [comment]
did you copy everything over? are you using the correct download?

**Comment by DeMoN100** [comment]
Yes I am

**Comment by theBGuy** [comment]
can you post a screenshot? Whats your info tag and profile name

**Comment by DeMoN100** [comment]
I got it to work this error happened because I did not use one of your example Profile names now that I put it in it works.
