### ISSUE TITLE
default.dbj reference error

### ISSUE THREAD

**Issue by MyNameSukks** [isid0re/SoloLeveling#278]
hi, so i ran the sololeveling bot just fine through NM. it struggled in hell so i decided to turn off the bot and go do some chaos/baal runs to level up and set up a script to have it mf in NM to find items and maybe make it a little easier for the bot to do hell. now when i try to run the bot, i get this error "default.dbj195 reference error: SetUp not defined" and the bot doesnt run. i use both my laptop and PC for botting, so i checked for the error in the default.dbj script, and i cannot see an error. both scripts look exactly the same on my laptop and PC, but ever since i ran the bot for mfing on my pc, the sololevel script wont work anymore. any thoughts?

**Comment by isid0re** [comment]
@DeMoN100 thanks for answering.
