### ISSUE TITLE
Necro Summon Struggling

### ISSUE THREAD

**Issue by DeMoN100** [isid0re/SoloLeveling#279]
Summon Necromancer build is what I am trying with this and when it seems to get to 80 this is when it really starts to struggle in hell. The bot has been dying more then accumulating xp 80-85 all I see in log is constant you died exp lost. Perhaps add a chicken option to auto exit game when below 20% hp?

**Comment by isid0re** [comment]
The necro should chicken in softcore at 10% but what your describing sounds like it's too squishy and getting 1shotted. Can you tell me what acts and areas it struggles in? 

Thanks.

**Comment by DeMoN100** [comment]
Act II is where it usually dies in hell it's been running all day dying gaining no exp it just loses it all on death & it does not chicken under 10% at all.

**Comment by DeMoN100** [comment]
Any update isid0re?

**Comment by isid0re** [comment]
I haven't had a chance to go thru the necro or any of the builds other than the paladin for late game play. I will be going thru late game play after I finish the barb start and leveling builds as well as the charms system.

Charms will definately alter the build strategies.
