### ISSUE TITLE
Config.Inventory[0] = [0,0,1,1,1,1,1,1,1,1];

### ISSUE THREAD

**Issue by gattarmax** [isid0re/SoloLeveling#282]
Config.Inventory[0] = [0,0,1,1,1,1,1,1,1,1];
Config.Inventory[1] = [0,0,1,1,1,1,1,1,1,1];
Config.Inventory[2] = [0,0,1,1,1,1,1,1,1,1];
Config.Inventory[3] = [0,0,1,1,1,1,1,1,1,1];

Inventory Settings
Why would I still move my belongings??
Thank

Which file should I set ?
_Originally posted by @gattarmax in https://github.com/isid0re/SoloLeveling/discussions/281_

**Comment by isid0re** [comment]
Inventory lock is not incorporated in the bot at this time
