### ISSUE TITLE
lightning sell sandstorm

### ISSUE THREAD

**Issue by fabio1999ita** [isid0re/SoloLeveling#286]
i try to drop whit another char sandstorm the bot pick it and it selled to akara

**Comment by aim2kill** [comment]
1st dropping items with another toon doesnt insured that the bot will keep and wear it and second if was in the last lighning build already the top tier for boot is war traveler.

**Comment by fabio1999ita** [comment]
ok, but sandstorm are really good

**Comment by isid0re** [comment]
a couple of things. 

the bot holds items in an array, so pausing the bot adding an item then starting the bot, the added item is not loaded into the array. so it will be flagged as unwanted and will be sold. this will happens regardless of the item. it could even be end game gear and it will still flag the item as unwanted. 

if you want to add gear by stopping and starting the bot, you will need to place the items in the stash and remake the sololeveling game. This will ensure your bot doesn't sell the item with the clearinventory function.
