### ISSUE TITLE
Error in SoloLeveling (sololeveling.js #2174

### ISSUE THREAD

**Issue by Safini323** [isid0re/SoloLeveling#29]
Hey
My Paladin Hammerdin(hell) came to act 3 travical and there comes up with this error 

09:08:02 (pal leveling) [Game: Hchgfhfg372//Fgbh (15:12)] [Level: 83 (50.51%)] [XP: 3686639] [Games ETA: 11]
09:21:18 (pal leveling)  Error in SoloLeveling (sololeveling.js #2174) target is undefined (Area: 83, Ping:125, Game: Hchgfhfg373)
09:21:18 (pal leveling) [Game: Hchgfhfg373//Fgbh (13:02)] [Level: 83 (53.52%)] [XP: 2401183] [Games ETA: 15]
09:32:36 (pal leveling)  Error in SoloLeveling (sololeveling.js #2174) target is undefined (Area: 83, Ping:78, Game: Hchgfhfg374)
09:32:36 (pal leveling) [Game: Hchgfhfg374//Fgbh (11:04)] [Level: 83 (56.20%)] [XP: 2142255] [Games ETA: 16]
09:45:08 (pal leveling)  Error in SoloLeveling (sololeveling.js #2174) target is undefined (Area: 83, Ping:78, Game: Hchgfhfg375)
09:45:08 (pal leveling) [Game: Hchgfhfg375//Fgbh (12:16)] [Level: 83 (60.68%)] [XP: 3577921] [Games ETA: 9]
09:59:49 (pal leveling)  Error in SoloLeveling (sololeveling.js #2174) target is undefined (Area: 83, Ping:79, Game: Hchgfhfg376)
09:59:49 (pal leveling) [Game: Hchgfhfg376//Fgbh (14:27)] [Level: 83 (66.11%)] [XP: 4345469] [Games ETA: 6]
10:02:00 (pal leveling) [Game: Hchgfhfg377//Fgbh (01:56)] [Level: 83 (66.66%)] [XP: 437752] [Games ETA: 61]

He then begins a new game: andy-Lower Kurast-travincal and  then this error comes up and it happens over and over and the bot does no progression

**Comment by isid0re** [comment]
thank you for your post. I am in the process of restructuring the code base. During this restructuring I will take a look at this situation. thank you again.

**Comment by isid0re** [comment]
a safety clause has been added for when the target is killed during pathing. this should fix the error and allow the bot to continue. additionally the bot structure has been completely redone into a modular format. please remove the old files and update to the most recent version. thanks

**Comment by Safini323** [comment]
Error in SoloLeveling (attackoverrides.js #21) target is undefined (Area: 37, Ping:110, Game: Ghrtuyhrty5)
