### ISSUE TITLE
 Error in SoloLeveling (attackoverrides.js #21) target is undefined (Area: 83, Ping:94, Game: Erter1)

### ISSUE THREAD

**Issue by Safini323** [isid0re/SoloLeveling#30]
again
 Error in SoloLeveling (attackoverrides.js #21) target is undefined (Area: 83, Ping:94, Game: Erter1)

**Comment by isid0re** [comment]
What difficulty is this error occurring in?

**Comment by Safini323** [comment]
hell,

**Comment by isid0re** [comment]
Ok. I am going to try and recreate this error so I can have it properly patched. Thanks.

**Comment by isid0re** [comment]
error has been patched.
