### ISSUE TITLE
throw junk

### ISSUE THREAD

**Issue by operation0017** [isid0re/SoloLeveling#300]
after loot cube, bot will go act4 buy potion then throw out all potion、TPbook，how to fix it ?

**Comment by isid0re** [comment]
You will need to update your files to the most recent push. This bug has been fixed as of yesterday's update

**Comment by operation0017** [comment]
thx ,I'll try it right now

isid0re ***@***.***> 於 2021年7月7日 週三 01:54 寫道：

**Comment by isid0re** [comment]
If it doesnt work please post back.
