### ISSUE TITLE
Critical problem with picking up body once dead

### ISSUE THREAD

**Issue by Sheep30** [isid0re/SoloLeveling#301]
Hello,

My SCCL sorc, my SCL hammerdins and Blizzballers sometimes die. No problème with it. Sadly sometimes they fail to get their body and SoloLeveling script doesn't stop! You heard me well, it process to goes to areas and kill mobs poorly geared.
Very scary, I was lucky enough to stop them manually (or they save&exit cuz low hp while fighting). If they had die, rip all my equipment...

(Latest update, never interacted myself with gear, no str glitched)

I would avoid using SoloLeveling for now.

Sheep.

**Comment by isid0re** [comment]
As we discussed on discord. The bot is a work in process. Additionally, you were using the bot to MF. That is not the bots design or purpose. 

Earlier versions didnt clear Inventory on start which would cause the body to not fully take if it was filled with picked items. This has been updated and will provide some inventory room for the bot if you dont overflow the bot with pickit items. (Kolbot doesnt stash items at startup)

I would recommend based on your current use and character levels to not use sololeveling.

The bot is designed for ONLY leveling and gearing up.

 As your characters per our conversation in discord had high level runewords, uniques, and were in the 90s for a character level, they clearly are well beyond the benefit of using sololeveling.
