### ISSUE TITLE
attack stuck

### ISSUE THREAD

**Issue by operation0017** [isid0re/SoloLeveling#302]
SCL-PAL 
ACT : 1   3
place : Dungeon
 
problem : if there monster behind the wall , bot has high chance stuck on the wall, and no give up

**Comment by Roycinger** [comment]
Afaik, isid0re is already working on this wallhugging issue.
As a temporary fix, you can pause the bot, move to the monster / location where the bot wants to walk to and resume the bot.

**Comment by isid0re** [comment]
Recent push has a prototype fix for the wallhugging. More testing will be needed before closing this issue.

**Comment by Roycinger** [comment]
Wallhugging still persists for me in Pits and Temple runs

![image](https://user-images.githubusercontent.com/7791335/126616007-1e675cd0-0c71-40c4-9d3f-5c4c3fa60e59.png)

**Comment by isid0re** [comment]
after discussing testing with discord has been confirmed fixed with latest push
