### ISSUE TITLE
Already equipped charms getting logged over and over again

### ISSUE THREAD

**Issue by Roycinger** [isid0re/SoloLeveling#308]
Hi,
already adressed this on Discord. However, this might be the proper place to track the issue.

I noticed that charms, that are already equipped, getting logged in the console over and over again.
For reasons of clarity and overview, this should be looked into.
![image](https://user-images.githubusercontent.com/7791335/126082755-3dc88f55-779f-4f8c-9a02-e093ce62723e.png)

edit:
I noticed that a unique ring is also being logged over and over again:
![image](https://user-images.githubusercontent.com/7791335/126301064-f576bde7-7f50-4dee-a9dd-bf5951a69590.png)

**Comment by Roycinger** [comment]
As a temporary workaround, I commented line 439 in ItemOverrides.js

**Comment by isid0re** [comment]
An update has been pushed which should correct the repetitive logging.

**Comment by Roycinger** [comment]
I installed the new files, no change for me here
![image](https://user-images.githubusercontent.com/7791335/126615747-6c305e04-4424-42eb-993a-b9bb0f80315a.png)

**Comment by Roycinger** [comment]
Fixed with commit e6cf19d
