### ISSUE TITLE
Undefined error in Config.Runewords on new Barb

### ISSUE THREAD

**Issue by randy-cruz** [isid0re/SoloLeveling#310]
[2021/07/23 11:56:21] <SCL-BARB> Pickit Tier (Tier) error! Line # 1 Entry: undefined (SoloLeveling) Error message: Config.Runewords[(intermediate value)][0] is undefined

New character, Frenzy build. Just merged the latest commits in and started this character about an hour ago.

**Comment by isid0re** [comment]
thank you i updated the typo in the barbarian.sololeveling.js config. to correct the issue. 
line 324  needsed to change  `Config.Runewords.push([Runeword.BoTD, "Colossus Blade"]);` to `Config.Runewords.push([Runeword.BreathoftheDying, "Colossus Blade"]);`
