### ISSUE TITLE
Paladin trashed slot 1 weapon after making Call to Arms in slot 2

### ISSUE THREAD

**Issue by ForestRock22** [isid0re/SoloLeveling#318]
![image](https://user-images.githubusercontent.com/21211675/127582332-1d5c1839-9bef-4ee0-9c32-c9bc9d2bb618.png)

**Comment by isid0re** [comment]
Thanks for posting I will look into why thst occurred.

**Comment by isid0re** [comment]
I havent forgotten about this. Finally got it to trigger the same reported issue. I'm working on a fix and will have it out soon.

**Comment by isid0re** [comment]
Bug has been fixed and the repo update has been pushed
