### ISSUE TITLE
Paladin keeping Wirefleece in inventory after town cleanup (Ethereal no slots)

### ISSUE THREAD

**Issue by ForestRock22** [isid0re/SoloLeveling#319]
![image](https://user-images.githubusercontent.com/21211675/127582789-2142a78b-33d1-4969-b09b-968e000d3191.png)

**Comment by isid0re** [comment]
The bot is preparing to cube the wire fleece  for an eth fortitude for the merc.

**Comment by ForestRock22** [comment]
Ah looks like it tried and failed I dont see any crashes around that time either

18:57:55 (SCL-PAL) Transmuting: Wire Fleece + Tal Rune + Thul Rune + Perfect Topaz
