### ISSUE TITLE
Please stop discarding junk and sell it

### ISSUE THREAD

**Issue by ircopdd** [isid0re/SoloLeveling#32]
![Ashampoo_Snap_2020年12月23日_12h58m08s_002_](https://user-images.githubusercontent.com/3633003/102961305-e946d180-451e-11eb-9612-16523b4f6667.png)
![Ashampoo_Snap_2020年12月23日_12h53m17s_001_](https://user-images.githubusercontent.com/3633003/102961309-ea77fe80-451e-11eb-8f78-541781f19b6d.png)

**Comment by isid0re** [comment]
It's something I'm working towards. There are lots of little connections between the various scripts.

**Comment by isid0re** [comment]
should be fixed now. won't sell all items but most are sold.
