### ISSUE TITLE
Fail to launch bot on a fresh install.

### ISSUE THREAD

**Issue by tianvay** [isid0re/SoloLeveling#33]
The following Errors show up:
First off: Error in sorceress.levelme.js(line62): Config.Hephasto is undefined.
I can just comment that one out, and line 63 as well, since they don't work.

Then we get Error in ntipoverrides.js(line19): itemString.toLowerCase(...).includes is not a function

We also get File(kolbot\libs\common\config.js:95) Error: Config.init: Error in character config.
Probably because LoadConfig.call() failed

**Comment by tianvay** [comment]
Solution is to remove the check for "tier" and the lowercase.include temporarily to start the bot.

**Comment by isid0re** [comment]
Actually, your problem is not my code but the kolbot installation you were using. Some files from your installation are from an older repo. You need to be using the https://www.github.com/blizzhackers/kolbot repo.
