### ISSUE TITLE
Error in SoloLeveling (pather.js #1372) getPresetUnits failed, couldn't access the level! 

### ISSUE THREAD

**Issue by Quest79** [isid0re/SoloLeveling#330]
`23:44:06 (SCL-sorc)  Error in SoloLeveling (pather.js #1372) getPresetUnits failed, couldn't access the level! (Area: 30, Ping:0, Game: )`

`00:01:35 (SCL-sorc)  Error in SoloLeveling (pather.js #1372) getPresetUnits failed, couldn't access the level! (Area: 31, Ping:15, Game: )`

`00:01:52 (SCL-sorc) D2BS is not responding... starting profile`

`00:06:37 (SCL-sorc) Made runeword: Stealth Studded Leather`

`00:13:25 (SCL-sorc)  Error in SoloLeveling (pather.js #1372) getPresetUnits failed, couldn't access the level! (Area: 30, Ping:0, Game: )`

`00:23:35 (SCL-sorc)  Error in SoloLeveling (pather.js #1372) getPresetUnits failed, couldn't access the level! (Area: 30, Ping:0, Game: )`

`00:23:51 (SCL-sorc) D2BS is not responding... starting profile
`

Any help in how to fix this? This is offline play.

**Comment by isid0re** [comment]
That's a known issue for single player. The problem is the map seed isnt properly rendering. I found the only fix was to load the game as host tcp/ip

**Comment by Quest79** [comment]
Thanks, I will just play in that mode then. This is a really good leveling script. Ive been watching it with delight.
