### ISSUE TITLE
How to skip cutscenes between acts

### ISSUE THREAD

**Issue by Slamzorer** [isid0re/SoloLeveling#331]
Hi! TY for your job first of all. I have an issue, I try google it and find fix but nothing helps. I am talking about  cutscenes between acts. I'll try to put -skiptobet in parameters but this not hlps. all my parameters are -w -sleepy -ftj -skiptobet - ns -lq

**Comment by tyson-dev** [comment]
try -skiptob**n**et first :D, afaik cinematics should'nt play in windowed mode at all, there shouldn't be a space in "- ns" also. Also also try not using "-lq" i guess

try "-w -sleepy -ftj -skiptobnet -ns" as parameters
