### ISSUE TITLE
Movespeed super slow.

### ISSUE THREAD

**Issue by Outlaw466** [isid0re/SoloLeveling#336]
Running a hammerdin script. It's currently on act 4 nightmare. Bot starts off smooth then throughout the game the movement speed is slower than walking. Full Stam, run toggled on, not frozen. The hammerdin is slow motion walking. Only fixes if I reset the game. Any fixes?

**Comment by FNCardascia** [comment]
Prior issues indicate it as a D2BS core issue. Nothing to do with the script.
