### ISSUE TITLE
Error in SoloLeveling (pather.js #1372) getPresetUnits failed, couldn't access the level! (Area: 30, Ping:0, Game: )

### ISSUE THREAD

**Issue by damienfayet** [isid0re/SoloLeveling#345]
Hello,

I encountered this issue in A1 prison with 3 of my 4 chars. Can you give me a little help/hint on how by pass this ?

Thanks,

**Comment by isid0re** [comment]
If you are playing on singleplayer then that is a bad map seed from d2.exe. the fix there is to use the tcpip host game option to reroll maps..
