### ISSUE TITLE
Error in SoloLeveling (patheroverrides.js #717) useUnit: Unit not found. TYPE: 5 ID: 49 AREA: 62 (Area: 62, Ping:0, Game: )

### ISSUE THREAD

**Issue by damienfayet** [isid0re/SoloLeveling#346]
Hello,

Having this issue a lot in Act2 with an elemental druid trying to get staff from maggot lair.

A little hint on why it's happening ?

Thanks,

**Comment by mintwzy** [comment]
I got similar error in Maggot Lair as Babarian && Druid. And here is what happens.

`d2bs/kolbot/libs/SoloLeveling/Scripts/staff.js` specifies what to do for the `staff` quest.
```javascript
	// Go to 
	// 	62 = Maggot Lair Level 1
	//	63 = Maggot Lair Level 2
	//	64 = Maggot Lair Level 3
	if (!Pather.moveToExit([62, 63, 64], true) || !Pather.moveToPreset(me.area, 2, 356)) {
		return false;
	}
```

Then in `d2bs/kolbot/libs/SoloLeveling/Functions/PatherOverrides.js` file `moveToExit` function
```javascript
					case 2: // stairs
						if (!this.openExit(areas[i]) && !this.useUnit(5, currExit.tileid, areas[i])) {
							return false;
						
```

Lastly in the same file `useUnit` function, after 5 retry, we got this error.
```javascript
Pather.useUnit = function (type, id, targetArea) {
	var i, coord, tick, unit, preArea = me.area;

	for (i = 0; i < 5; i += 1) {
		unit = getUnit(type, id);

		if (unit) {
			break;
		}

		delay(200);
	}

	if (!unit) {
		throw new Error("useUnit: Unit not found. TYPE: " + type + " ID: " + id + " AREA: " + me.area);
	}
```
------------------------
Unluckily, I didn't find a good solution for this, so I increase the try numbers for each script. This solves the problem for my Druid but not Barbarian...Hope someone can share more info on this, thanks~

`d2bs/kolbot/libs/bots/SoloLeveling.js`

```javascript
			let retries = 10;

				for (j = 0; j < retries; j += 1) {
					if (this[SetUp.scripts[k]]()) {
						break;
					}
				}
```

**Comment by isid0re** [comment]
Please update your files using the latest update from the repo. I've included a fix in pather for this issue on the last commit.
