### ISSUE TITLE
No Spare-Mana in inventory

### ISSUE THREAD

**Issue by tyson-dev** [isid0re/SoloLeveling#350]
Seen this now on scl and sccl cold and blizzballer. At level 59 Nightmare, inventory after merchant just the few rejuvs, she doesn't buy mana pots which makes her go town way too often.

Edit: Maybe the better balance for belt would be 2columns Heal, 1 mana, 1 rejuv and more mana in inventory.

**Comment by mintwzy** [comment]
You can change the following Belt & Inventory settings for your character to change belt configuration and number of extra potion in inventory.

`d2bs/kolbot/libs/config/Sorceress.SoloLeveling.js`

```javascript
	/* Belt configuration. */
	Config.BeltColumn = ["hp", "mp", "mp", "rv"];
	Config.MinColumn[0] = Config.BeltColumn[0] !== "rv" ? Math.max(1, Storage.BeltSize() - 1) : 0;
	Config.MinColumn[1] = Config.BeltColumn[1] !== "rv" ? Math.max(1, Storage.BeltSize() - 1) : 0;
	Config.MinColumn[2] = Config.BeltColumn[2] !== "rv" ? Math.max(1, Storage.BeltSize() - 1) : 0;
	Config.MinColumn[3] = Config.BeltColumn[3] !== "rv" ? Math.max(1, Storage.BeltSize() - 1) : 0;

	/* Inventory buffers and lock configuration. */
	Config.HPBuffer = 0;
	Config.MPBuffer = 0;
	Config.RejuvBuffer = me.findItems(605, -1, 3).length >= Item.getCharmLimit(605) ? 0 : 4;
```

Reference:

- [https://github.com/blizzhackers/documentation/blob/master/kolbot/CharacterConfig.md/#character-configuration](https://github.com/blizzhackers/documentation/blob/master/kolbot/CharacterConfig.md/#character-configuration)

**Comment by tyson-dev** [comment]
Thanks for your fast answer M8, doesn't work for my classic Sorc though. I do see"!me.classic" in that config file on some items, do i have to throw it in soemwhere for the belt/mana config?

**Comment by isid0re** [comment]
Look at the libs/config/builds/ autobuild templates both leveling and your finalbuild. Those settings override the character config class.sololeveling.js file

**Comment by tyson-dev** [comment]
Thanks awesome, also here's my cleaned out "chest"-list Isid0re from misc_overrides.js, really nice you already implemented that.
As expected, atm she's cracking barrels @ coutness in hell and i guess chars in tombs are affected also.
Feel free to copy paste :D

"chest", "loose rock", "hidden stash", "loose boulder", "corpseonstick", "armorstand", "weaponrack", "roguecorpse", "corpse", "chest3", "skeleton", "guardcorpse", "stash", "hollow log", "skullpile", "skull pile", "bonechest", "woodchestl", "woodchestr", "barrel wilderness", "burialchestr", "burialchestl", "chestl", "chestr", "deadperson", "deadperson2"

**Comment by isid0re** [comment]
Thanks I'll add that into the next push
