### ISSUE TITLE
Sorc error in single player : Error in SoloLeveling (patheroverrides.js #727) useUnit: Incomplete quest. (Area: 120, Ping:0, Game: )

### ISSUE THREAD

**Issue by damienfayet** [isid0re/SoloLeveling#355]
Hello,

I have this one quite often playing my Sorc in singleplayer. (seems to be only with Sorc).

Do you have a little hint to fix it ?

Thanks !

**Comment by mintwzy** [comment]
```javascript
120 = Arreat Summit
```

You will get this error if you try to enter The World Stone without finishing Arreat Summit quest. 

Sorc may use up all the potions and TP back town, then she will try to enter The World Stone and get this error. Try to manually finish the Arreat Summit quest, or wait for you Sorc to be strong enough to finsih the Arreat Summit without going back to town.

https://github.com/blizzhackers/kolbot/blob/dbb028623b144728e9bd47cf420b5006524f4d98/d2bs/kolbot/sdk/areas.txt

**Comment by damienfayet** [comment]
All quests were validated but ok, I will fix it, thanks !
