### ISSUE TITLE
Assassin Error Error in SoloLeveling (patheroverrides.js #431) moveToPreset: Couldn't find preset unit - id 152 (Area: 40

### ISSUE THREAD

**Issue by gr33k** [isid0re/SoloLeveling#358]
Act 2 I believe provides the following error and restarts:

Error in SoloLeveling (patheroverrides.js #431) moveToPreset: Couldn't find preset unit - id 152 (Area: 40)

```
Pather.moveToPreset = function (area, unitType, unitId, offX, offY, clearPath, pop) {
	if (area === undefined || unitType === undefined || unitId === undefined) {
		throw new Error("moveToPreset: Invalid parameters.");
	}

	if (offX === undefined) {
		offX = 0;
	}

	if (offY === undefined) {
		offY = 0;
	}

	if (clearPath === undefined) {
		clearPath = false;
	}

	if (pop === undefined) {
		pop = false;
	}

	var presetUnit = getPresetUnit(area, unitType, unitId);

	if (!presetUnit) {
		throw new Error("moveToPreset: Couldn't find preset unit - id " + unitId);
	}

	return this.moveTo(presetUnit.roomx * 5 + presetUnit.x + offX, presetUnit.roomy * 5 + presetUnit.y + offY, null, clearPath, pop);
};
```
Didn't seem to be an issue in pre-Hell runs that I can tell

**Comment by isid0re** [comment]
Please confirm that you are using the most recent updates. Pather issues were addressed a couple commits prior to your submitted post.

**Comment by gr33k** [comment]
I updated just in case - I think it was related to the staff. Manually made it and had it on me (not stash) and it finished the staff quest and Duriel successfully! Closing this out ty @isid0re
