### ISSUE TITLE
Hammerdin not using hammers

### ISSUE THREAD

**Issue by ARolf60** [isid0re/SoloLeveling#359]
At level 19 the Hammerdin profile respecs and places blessed hammer on the left mouse button.
The paladin, from this point onward, will position himself next to a mob and idle until the merc kills the monster

expected behavior:
paladin will use any left lick ability

Additional details:
Solo (non battle.net) 1.14D
No additional mods installed

**Comment by MazeEQ** [comment]
Try disabling:
Config.PacketCasting = 1;

in libs\config\Yourscript

**Comment by isid0re** [comment]
I recently changed the location for the respec variable. It may have inadvertantly affected how i am handling the respec.

To verify it is an issue, please go to
Sololeveling/tools/developer.js 

And turn ForcePACKETCASTING false

Please let me know the results.

If it still doesnt respec or attac then that will be a confirmed issue. 

Thanks.

**Comment by ARolf60** [comment]
@isid0re 
changing the "ForcePACKETCASTING" to false fixed the issue
