### ISSUE TITLE
Not pressing trade / repair

### ISSUE THREAD

**Issue by Frankie429** [isid0re/SoloLeveling#36]
Hello I just started using this script, and watching my characters I noticed they will talk to akara / charsi in A1 but not actually select trade / repair from either of them so they'll just stand there for a while.

Could I have done something wrong or is anyone getting this issue?

How could I fix?

Thanks in advance

**Comment by theBGuy** [comment]
it uses packetShopping, press home and you'll see its actually interacting with the npcs

**Comment by Frankie429** [comment]
My characters just stand there confirmed I'm watching them they wont buy potions / clear inventory unless I manually click trade

Could I have set something up wrong? I appreciate your quick response, sorry I'm pretty new to kolbot.

Everything else seems to be working great

**Comment by Frankie429** [comment]
Yeap you're right! Sorry about the confusion I'm pretty new.

I appreciate your quick response.

**Comment by isid0re** [comment]
@theBGuy Thanks for explaining for me.
