### ISSUE TITLE
Error in SoloLeveling (patheroverrides.js #253) SoloLeveling: Failed to change Act (Area: 40, Ping:32, Game:)

### ISSUE THREAD

**Issue by togari1360** [isid0re/SoloLeveling#360]
Duriel didn't die, but character teleports over the map 
going to proceed next act

**Comment by isid0re** [comment]
Thanks for posting. Can you tell me the difficulty, character level, and version of d2 you are playing?

**Comment by togari1360** [comment]
> Thanks for posting. Can you tell me the difficulty, character level, and version of d2 you are playing?

difficulty: nightmare and hell, character level 65~75 sorceress

**Comment by isid0re** [comment]
Is this on classic, LOD, or are you playing a modded D2?

**Comment by togari1360** [comment]
> Is this on classic, LOD, or are you playing a modded D2?

I'm playing on Lod.

**Comment by isid0re** [comment]
Fixed in earlier commit. Closing.
