### ISSUE TITLE
Pausing bot

### ISSUE THREAD

**Issue by tamkaho** [isid0re/SoloLeveling#364]
Sometimes I'd like to press pause when character is in town to check things out. However, bot always seems to continue running. Do you know why?

**Comment by isid0re** [comment]
So it sounds like you are attempting to pause the bot when it returns midscript to town and performs its own chores. 

What is actually happening if that is the case is:

The bot pauses itself to go to town and perform tasks like buy potions, revive merc,  clear inventory to make room, etc. (Default kolbot functionality) 

So when you are pausing the bot manually you actually are unpausing the script. Which causes it to post move retry a few times and reorient itself then continues to run.

If you wish to pause the bot. The best time to do so is not when the bot goes to town, but rather while it is not in town.
