### ISSUE TITLE
Ancients boss fight Act V bug

### ISSUE THREAD

**Issue by jagarop** [isid0re/SoloLeveling#365]
When doing the Ancients fight in Act V, if your bot port out to city (e.g. life went too low / went out of potions) this boss encounter will reset due intended game mechanics.

But instead of trying to defeat the boss again, the bot will try to move to Worldstone Keep resulting in the following error:

13:14:17 (SCL-PAL-001)  Error in SoloLeveling (patheroverrides.js #727) useUnit: Incomplete quest. (Area: 120, Ping:0, Game: )
13:14:34 (SCL-PAL-001) D2BS is not responding... starting profile

**Comment by isid0re** [comment]
After discussing on discord, issue was due to not having the updated default.dbj installed. Closing issue.
