### ISSUE TITLE
Necro makes Heart of the Oak then trashes it

### ISSUE THREAD

**Issue by ForestRock22** [isid0re/SoloLeveling#366]
Hi, 

I noticed this again today, necro is level 89 and using Boneshade Lich Wand in slot 1 and Call To Arms in slot 2.

He finds a superior flail 4 sockets and keeps it in bank until he can make Heart of the Oak but then never equips it and trashes it.

**Comment by ForestRock22** [comment]
This time he had enough dex to equip it

**Comment by isid0re** [comment]
Forest please update ALL of your sololeveling files including the default.dbj. it sounds like you were using an older version.

**Comment by ForestRock22** [comment]
I usually just download the zip and replace everything but I downloaded again yesterday so ill keep an eye out if it comes back.

**Comment by isid0re** [comment]
Thanks, I had believed that the issue was fixed. I'll close the issue out for now. If it happens again please open an issue. Thanks again.
