### ISSUE TITLE
rwBase undefined bug

### ISSUE THREAD

**Issue by SonnyMunchkin** [isid0re/SoloLeveling#368]
The bot will go to his "stalling" phase when he makes a new runeword or has a runeword that is too high for it to use.  I usually sell the new base or runeword item and it seems to help.

**Comment by isid0re** [comment]
Hi. Thanks for posting. Can you please check your file sololeveling/functions/townoverrides.js

Make sure line 1137 says `switch (check)` 

If it says `switch (focus)` then please update your townoverrides.js file. And see if the error still continues.

**Comment by SonnyMunchkin** [comment]
> Hi. Thanks for posting. Can you please check your file sololeveling/functions/townoverrides.js
> 
> Make sure line 1137 says `switch (check)`
> 
> If it says `switch (focus)` then please update your townoverrides.js file. And see if the error still continues.

I get an error when trying to open the javascript file.

**Comment by isid0re** [comment]
Open the file in a text editor like notepad. And you wont get an error

**Comment by SonnyMunchkin** [comment]
Ok.  I deleted the old file and replaced it with the new TownOverrides that was just recently released.  I will let you know if that solves it if you would like.

**Comment by isid0re** [comment]
Please let me know your results. Thanks
