### ISSUE TITLE
Character attacking once every few seconds

### ISSUE THREAD

**Issue by mato89** [isid0re/SoloLeveling#371]
Just created a new char (hammerdin). It seems to be attacking once every few seconds instead of attacking continuously. Any idea why?

**Comment by mato89** [comment]
This also applies to melee. Only seems to happen to low level chars.

**Comment by isid0re** [comment]
I've gone thru the code base in an audit and clean up. Removing redundant code from earlier implementations and ideas. Doing so has improved performance in attacks. Please update to the most recent push.
