### ISSUE TITLE
D2BS is not responding

### ISSUE THREAD

**Issue by Ihja** [isid0re/SoloLeveling#379]
Hi, D2BS is not working. I got msg on Console part of D2BS that there is no respond. All the chars created get the same message.
Doble check it and today, same result. Before was everything ok, two chars are on lvl 90, necro 47. On regular D2BS works perfect. 

12:59:26 (SCL-SORC) D2BS is not responding... starting profile
12:59:37 (SCL-SORC) D2BS is not responding... starting profile
12:59:49 (SCL-SORC) D2BS is not responding... starting profile
13:00:46 (SCL-PAL) D2BS is not responding... starting profile
13:00:57 (SCL-PAL) D2BS is not responding... starting profile
13:01:24 (SCL-NECRO) D2BS is not responding... starting profile
13:01:35 (SCL-NECRO) D2BS is not responding... starting profile

**Comment by isid0re** [comment]
Do a reinstall of the dependencies. This tends to happen when Microsoft does an update and the pc doesnt shut down properly.
