### ISSUE TITLE
stuck at diablo

### ISSUE THREAD

**Issue by MyNameSukks** [isid0re/SoloLeveling#38]
not really an issue, more of a question, but is it common for a sorc to get stuck at diablo? it never has enough money and uses pots so fast it runs out halfway through opening seals, then it just goes to hit things. i let the but go for a whole night to see if it would eventually get through it, but it didnt, it was just leaving when it almost dies and then going back in, over and over again. is there something i can do to help it finish the area and move on?

**Comment by isid0re** [comment]
What difficulty and level is the sorc?

**Comment by MyNameSukks** [comment]
normal, lvl 31

**Comment by isid0re** [comment]
That's not a common situation. It seems that its run out of gold to keep the wheels moving so its stalling out. So if you pause the bot and run some areas like countess and andy for quick items to sell to get around 25k-50k that should fix the problem currently. 

While its not common, it can derail the progression. So I will work out a solution so this doesnt occur. Thanks.

**Comment by MyNameSukks** [comment]
will do, thanks for the tip.
