### ISSUE TITLE
For Socket Mules, InfoTag must say "Socketmule". Not "Socket".

### ISSUE THREAD

**Issue by Unrelentful** [isid0re/SoloLeveling#394]
For Socket Mules, InfoTag must say "Socketmule". Not "Socket".
The Github page states just "Socket" will work, but it didn't for me. I had to put in "Socketmule".

**Comment by isid0re** [comment]
"Socketmule" wouldn't work on sololeveling the code base in globals.js line 580 says:

 ` if (SetUp.finalBuild === "Bumper" || SetUp.finalBuild === "Socket") {`
Sounds like you've mixed and matched other projects with sololeveling.
