### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by ebner20** [isid0re/SoloLeveling#45]
First things first.  Thanks for using time to create these scripts.  Its nice to have another autoleveler for other classes than sorceress available.  Ive been using the Necro leveler and have made a few observations. 

1.  It stalls a few seconds before talking to anyone in town.  Not such a big deal but when it talks to 3 nps each time it ports to town it really adds up.
2. Speaking of porting to town, it does this an awful lot.  Im talking if it finds any blue/yellows on ground.  Which is quite often.  Adding to issue in number 1 it is slow going.  I started this profile at 5pm and its now 2am as I left him to his own devices after watching for the first hour and than last half hour before pausing it.  
3. I noticed that bot filled up stash with some large weapons for merc, armors and helm but never equipped the merc with them.  Merc had no items equipped before I paised and checked things out at 2am.  I clean the stash out and equipped the best that was stashed and turned the bot back on.
4. 9 hours into running script and it just now completed cube run.  Maybe its just bad luck on my end but I would have thought it would have been further.  He started piecing the staff back together and then had a failed to use portal error and left game.
5. Upon returning, the bot than started the run back up by starting with countess in act 1.  Not sure why but I left it and will check again in a few hours to see where its at.

Im using necro and edited the configuration file to end up with a summon build.  The setup was on a fresh copy of kolbot.  Followed your install direction exactly.  

Im here to adjust whatever you need me to and u will continue to give more feedback when I have it.  My plan is to startup another necro tomorrow with another build and watch it.  Ill start new thread on that as well when I find odd behavior.

Thanks again.  Im excited to test your other builds and can beta test others for you if you're working on other builds.  Just let me know.  H

**Comment by isid0re** [comment]
First,Thank you for testing. 

As for equipping items. There was an omission on my part in the code and would equip items on the merc. That has been fixed as of today's updates. So please update your files to the most recent. 

As for necros speed. Hes pretty slow till level 18 once he gets bone spear. Then he speeds up alot. 

Regarding the stalling with npc. I haven't noticed this but I will definately investigate it thanks. 

As for going to town alot. I am testing whether using lowgold is beneficial or not. As it gathers junk to sell it can increase time in town.  I haven't found a sweet spot yet. 

Again thanks for your posting and help.
