### ISSUE TITLE
pal blocked by a wine barrel.

### ISSUE THREAD

**Issue by ircopdd** [isid0re/SoloLeveling#5]
Pal wants to open the chest in the room, but the door is blocked by a wine barrel.

Difficulty in hell

Loop
move retry1
move retry2
move retry3

**Comment by isid0re** [comment]
can you provide which area this occured?

**Comment by ircopdd** [comment]
> 您能提供發生在哪個區域？

mausoleum 

gold chest

**Comment by ircopdd** [comment]
![Ashampoo_Snap_2020年11月17日_08h00m57s_003_](https://user-images.githubusercontent.com/3633003/99345561-89c92680-28cd-11eb-8b86-94fc92e61007.png)

**Comment by isid0re** [comment]
thank you. I found the problem and will push the fix shortly. You will need to update your config files and the script for the fix to take effect.
