### ISSUE TITLE
Error at Duriel

### ISSUE THREAD

**Issue by Despex94** [isid0re/SoloLeveling#56]
Hi Isid0re,
I use 4 bots with your scripts but they are stuck at Duriel. 
They don't take the staff from the stash and then place it in the orifice.

Error in SoloLeveling (pather.js #817) useUnit: Unit not found. ID: 100 (Area: 66, Ping:0, Game: )

Ps: I love your script and look forward to your future updates, Good Job m8.

**Comment by isid0re** [comment]
Please update to the most recent push as of yesterday. I have updated the questing functions to correct for this exact problem.

**Comment by Despex94** [comment]
Problem solved, I must have made an error the first time I downloaded the new version because the second time it corrected the problem. Thank you.
