### ISSUE TITLE
difficulty i setting is highest ,but bot is auto setting nightmare. why?

### ISSUE THREAD

**Issue by wcg928** [isid0re/SoloLeveling#63]
difficulty i setting is highest ,but bot is auto setting nightmare. why?

**Comment by ebner20** [comment]
I believe it stays and farms Nightmare until it reaches a certain point of resistance with gear to enter and survive in Hell.

**Comment by isid0re** [comment]
But has level caps before entering the next difficulty. If the level is under 37 or 67 it wont progress to nightmare or hell, respectively. Experience gain from cows, diablo, and baal runs is better under those levels than starting the next difficulty. Entering the next difficulty underlevelled increases the chance of the bot failing to progress and stalling out. Plus it has a chance to better equip itself from the runs.

**Comment by wcg928** [comment]
![222](https://user-images.githubusercontent.com/13197148/104906424-a4e40f80-59be-11eb-9f8e-64202847d43c.png)
this setting?

**Comment by ebner20** [comment]
Leave that on Hell always.
