### ISSUE TITLE
Can a barb solo Lvling be done? It will be good if a ww barb can be made, sorry not sure if this is the place to request

### ISSUE THREAD

**Issue by j4sp3r89** [isid0re/SoloLeveling#8]

**Comment by isid0re** [comment]
Yes a I do have plans for a whirlwind barb to be made. It is on my todo list. Currently, I'm finishing the necro and amazon config/builds before I start the barb.

**Comment by casualBotter** [comment]
it would probably be the most difficult/slowest class to solo, but in theory yes
