### ISSUE TITLE
Giving me this error despite following instructions perfectly.

### ISSUE THREAD

**Issue by neurological1** [isid0re/SoloLeveling#80]
did everything as the readme said, upon entering a game it gives me this error:

https://gyazo.com/387d3f668fbd4b81fd0f316dc0c23fe1

thanks for any help <3

**Comment by isid0re** [comment]
Please confirm that you are using the kolbot installation from https://www.github.com/blizzhackers/kolbot. Other repos are not certain to work and can cause this and other problems.

**Comment by isid0re** [comment]
No response after a week. Will assume this has been fixed. Closing.
