### ISSUE TITLE
reference to undefined property stringArray error

### ISSUE THREAD

**Issue by cable-one** [isid0re/SoloLeveling#85]
Hello,

Iam getting this error pretty mucht every time.

D2BS 16468: [Strict Warning] Code(162) File(c:\kolbot\d2bs\kolbot\libs\sololeveling\functions\ntipoverrides.js:159) reference to undefined property stringArray[i]
Line: (null)

It is preventing the bot form continuing.
This is happening in at hepasto.
It pick up the hammer and afterwards i get this message.
The bot leaves the game and starts over.

I have checked the code at the mentioned line
rval.line = stringArray[i].file + " #" + stringArray[i].line;

I can only assume it is the space that is messing up somehting  " #"

**Comment by isid0re** [comment]
Have you made any edits to the functions, hellforge script, or added any pickit files?

**Comment by cable-one** [comment]
HI,

Thanks you for your quick awnser.
Ive done some more testing and the code is just fine it seems.

The issue started to pop up when the bot was doing hepasto (destroying the soulstone)

My inventory was full, so there was no room to pick up the hammer.
Or it could not equip the hammer.

As a temp solution i have done the quest manually.

When this happens on hell difficulty i will report back!

**Comment by isid0re** [comment]
No further updates so closing.
