### ISSUE TITLE
ERROR  getMercFix is not a function

### ISSUE THREAD

**Issue by nemum** [isid0re/SoloLeveling#90]
Help my bro,

Error in SoloLeveling (miscoverrides.js #322) getMercFix is not a function (Area: 1, Ping:281, Game: Sep4)

**Comment by isid0re** [comment]
This error shows up when someone has edited a file in the functions folder and created a typo. What did you change/edit?

**Comment by isid0re** [comment]
another possibility is that you inputted the final build with a typo in the info tag area. 
please let me know if the issue was corrected for you so I can close this out. thanks.
