### ISSUE TITLE
Character keeps attacking even after boss is long dead

### ISSUE THREAD

**Issue by chaospoc** [isid0re/SoloLeveling#91]
Hello,

using druid leveling script, currently level 55 in nm.
This doesn't happen all the time but very frequently.
When doing the usual mf runs the druid will keep sending tornados long after Andariel or Mephisto is dead.
He will keep doing this until he has no mana potions, triggering a town refill, then goes back spamming tornados.

After some times, he will eventually decide it's enough and proceed with the run.

**Comment by isid0re** [comment]
Hmm. I haven't seen this. Are you playing on a server or tcp/ip or single player?

I ask because I'm wondering if it is a desync of some kind. Where its not catching the is target.dead flag. 

Thanks for posting and any additional information you can provide would be helpful.

**Comment by chaospoc** [comment]
Yes, this is on single player, it definitely looks like he still thinks the target is not dead. This doesn't happen for the necro, paladin or sorceress. They sometimes idle for 10-15 seconds after the boss is dead before moving on. The druid will sometimes do this 15 seconds wait then move on but usually he just spams tornados for 5 mins before he considers that the boss might be dead (lol).

I first noticed the druid doing this with baal, I was then able to confirm he does it with Andariel and mephisto too.

More infos,
I am running 4 sorceresses, 2 paladins, 1 druid and 1 necro at the same time in single player.
I didn't edit the scripts or js files.
Manual pausing will make him pause, but resuming will continue his assault on poor dead mephisto.
config info tag -> Wind

As of right now, typing this, he did manage to reach hell all by himself.
While this is minor, it's funny to watch the necro beat him in the race.
