### ISSUE TITLE
Using this overnight seems to randomly break my entire Kolbot

### ISSUE THREAD

**Issue by elninost0rm** [isid0re/SoloLeveling#96]
Hi there,

So I like your script and I've been using it to make hammerdins.  That said, I use a fresh, clean, latest Kolbot install when running this script and here's why.

After the first night of using this, I wake up to a "D2 as a problem and must close :(" error message.  Okay, no big deal.  Happens randomly no matter what script I'm using.  But after that, my entire Kolbot folder is borked.  Nothing runs.  Not even other profiles, like my manual play profiles.  Every single one gets this:

![image](https://user-images.githubusercontent.com/20605290/107948598-12557280-6f62-11eb-8cc6-b732a1c7e755.png)

I can't figure out how something so permanent could happen by the script erroring out and restarting.  This has happened twice now, and the original time, I merged Sololeveling into my main Kolbot folder, and that was rough since I had to manually "clean" the install by replacing everything except my configs, etc., just to get it working again.

Any ideas? It's like after this error occurs (whatever it is, can't find it in the logs anywhere), the bot can no longer find any files to run.  It's like it can't see or load anything after that.

**Comment by isid0re** [comment]
So I was able to recreate this situation by running multiple bots simultaneously.  Can you confirm that you were also running multiple bots when this happened? 

It appears that multiple connections (read/writes) at the same time corrupted the d2bs.ini file as they compete with each other and lock up the bot. To prevent this from happening, I have added random short delays to the entry script. 

Please update to the most recent files as  of this post and PLEASE let me know if it happens again for you.

As a quick fix so you dont have to reinstall everything. You can just reinstall (revert if you use svn checkout) of the d2bs.ini file and it will correct the problem for you. 

Thanks for posting this problem.

**Comment by elninost0rm** [comment]
Hi there!  Thanks so much for replying and taking the time.  So I can confirm that I am only running this single Kolbot / D2 instance on my actual PC, but I do have 3 separate VMs running on different VPN IPs.  They're all utilizing/linked to a totally different Kolbot folder, though, so I can't imagine that caused any problem.

Good to know about d2bs.ini regardless, though.  If it happens again, I'll just replace that instead of the whole installation, lol.

Sorry I wasn't able to help isolate further with this response.

**Comment by isid0re** [comment]
I guess the better way to say what I am asking would be how many profiles were you running? 

I also only have 1 kolbot profile and was only able to recreate this problem when I turned on 4 profiles to run at the same time.

**Comment by elninost0rm** [comment]
Oh, I see what you mean.  Yes, on this physical PC (not including the VMs), I am only running one kolbot which is running the single profile.

Just to remove the possibility, I deleted all other profiles from the Sololeveling Kolbot folder except for SCL-PAL, the single paladin leveling at the moment.

**Comment by isid0re** [comment]
Alright. Also to confirm you updated to the most recent push?

**Comment by elninost0rm** [comment]
I don't see a commit that is more recent than 11 hours ago.  Is that right?  Just making sure.

**Comment by isid0re** [comment]
That is correct. That was the last push.

**Comment by elninost0rm** [comment]
Yup, I'm all set.

**Comment by isid0re** [comment]
Please let me know if it happens again after letting it run for a couple days.  Thanks.
