### ISSUE TITLE
Bot won't enter Hell due to negative CR despite creating Ancient's Pledge (seemingly repeatedly) then ditching the shield

### ISSUE THREAD

**Issue by elninost0rm** [isid0re/SoloLeveling#97]
Hi there,

So not really a "bug" necessarily and maybe a miscalculation in logic, but I've noticed my hammerdin is hanging out in nightmare and he's almost level 69.  What's holding him back is his cold resist (-12 in hell), but instead of equipping Ancient's Pledge (despite crafting it, sometimes more than once, based on the log, I think), it then ditches the shield and continues using a +3 pcombat shield instead.  Obviously +3 pcombat is pretty nice, but why is the bot making Ancient's Pledge only to discard it?  That would certainly remove the Hell resistance logic barrier setup at a cost of a small amount of hammer damage.

Thoughts welcome.

**Comment by isid0re** [comment]
So in earlier config files, the autoequip tiers were located underneath the runeword setup causing the checks to make runewords (item.getequippeditem().tier) to return -1. This was corrected in the most recent push and will prevent the bit from remaking runewords.

As for the leveling. The cap is set to 35 or 65 if resistances are met. but if they are not a progression check occurs at levelcap + 5 to force the bot to move on to the next difficulty. So I  your case it would move to hell at 70.

**Comment by elninost0rm** [comment]
Gotcha, good to know.  Thanks!
