### ISSUE TITLE
Character's running super slow in game and sometimes can't login

### ISSUE THREAD

**Issue by Fittycal** [isid0re/SoloLeveling#99]
I doubt this is an issue with the SoloLeveling script but sometimes when in game my characters will start running suuuuuper slow.  I'm not sure if this is a configuration setting or a user settings somewhere.  Also I see an issue when trying to log in, sometimes it will just sit at the login screen and not enter anything and just stall out.  Again not sure if this is a configuration setting on my end or what the deal is.

**Comment by theBGuy** [comment]
running super slow is a game bug. Can you give more info for the login issue

**Comment by Fittycal** [comment]
Ah got it, I wonder if there is a quick fix for that other than creating a new game.  As far as the logging in issue, I followed steps 1-11 in the usage and sometimes it will just sit at the login screen and not type out anything as if it doesn't know what to put in the username/pass fields.  It doesn't happen every time but often enough.  Right now I have my diablo 2 game.exe's set to compatibility mode: XP SP2 and running as admin and the Kolbot program running in compatibility mode for Win7 and also running as admin.

**Comment by isid0re** [comment]
Fittycal,

Could you update to the most recent repo push dated 2/14 and let me know if it continues?

The login issues should be resolved regarding settings. I have recently pushed another patch to fix the bot erroring on multiple profiles logging in at the same time.

**Comment by Fittycal** [comment]
The most recent update seems to have fixed the login issues.
